/* Generated by Yosys 0.9+4052 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module wb_host(wbm_rst_i, wbm_clk_i, wbm_cyc_i, wbm_stb_i, wbm_adr_i, wbm_we_i, wbm_dat_i, wbm_sel_i, wbm_dat_o, wbm_ack_o, wbm_err_o);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire \reg_0[0] ;
  wire \reg_0[10] ;
  wire \reg_0[11] ;
  wire \reg_0[12] ;
  wire \reg_0[13] ;
  wire \reg_0[14] ;
  wire \reg_0[15] ;
  wire \reg_0[16] ;
  wire \reg_0[17] ;
  wire \reg_0[18] ;
  wire \reg_0[19] ;
  wire \reg_0[1] ;
  wire \reg_0[20] ;
  wire \reg_0[21] ;
  wire \reg_0[22] ;
  wire \reg_0[23] ;
  wire \reg_0[24] ;
  wire \reg_0[25] ;
  wire \reg_0[26] ;
  wire \reg_0[27] ;
  wire \reg_0[28] ;
  wire \reg_0[29] ;
  wire \reg_0[2] ;
  wire \reg_0[30] ;
  wire \reg_0[31] ;
  wire \reg_0[3] ;
  wire \reg_0[4] ;
  wire \reg_0[5] ;
  wire \reg_0[6] ;
  wire \reg_0[7] ;
  wire \reg_0[8] ;
  wire \reg_0[9] ;
  wire \reg_1[0] ;
  wire \reg_1[10] ;
  wire \reg_1[11] ;
  wire \reg_1[12] ;
  wire \reg_1[13] ;
  wire \reg_1[14] ;
  wire \reg_1[15] ;
  wire \reg_1[16] ;
  wire \reg_1[17] ;
  wire \reg_1[18] ;
  wire \reg_1[19] ;
  wire \reg_1[1] ;
  wire \reg_1[20] ;
  wire \reg_1[21] ;
  wire \reg_1[22] ;
  wire \reg_1[23] ;
  wire \reg_1[24] ;
  wire \reg_1[25] ;
  wire \reg_1[26] ;
  wire \reg_1[27] ;
  wire \reg_1[28] ;
  wire \reg_1[29] ;
  wire \reg_1[2] ;
  wire \reg_1[30] ;
  wire \reg_1[31] ;
  wire \reg_1[3] ;
  wire \reg_1[4] ;
  wire \reg_1[5] ;
  wire \reg_1[6] ;
  wire \reg_1[7] ;
  wire \reg_1[8] ;
  wire \reg_1[9] ;
  wire reg_ack;
  wire \reg_rdata[0] ;
  wire \reg_rdata[10] ;
  wire \reg_rdata[11] ;
  wire \reg_rdata[12] ;
  wire \reg_rdata[13] ;
  wire \reg_rdata[14] ;
  wire \reg_rdata[15] ;
  wire \reg_rdata[16] ;
  wire \reg_rdata[17] ;
  wire \reg_rdata[18] ;
  wire \reg_rdata[19] ;
  wire \reg_rdata[1] ;
  wire \reg_rdata[20] ;
  wire \reg_rdata[21] ;
  wire \reg_rdata[22] ;
  wire \reg_rdata[23] ;
  wire \reg_rdata[24] ;
  wire \reg_rdata[25] ;
  wire \reg_rdata[26] ;
  wire \reg_rdata[27] ;
  wire \reg_rdata[28] ;
  wire \reg_rdata[29] ;
  wire \reg_rdata[2] ;
  wire \reg_rdata[30] ;
  wire \reg_rdata[31] ;
  wire \reg_rdata[3] ;
  wire \reg_rdata[4] ;
  wire \reg_rdata[5] ;
  wire \reg_rdata[6] ;
  wire \reg_rdata[7] ;
  wire \reg_rdata[8] ;
  wire \reg_rdata[9] ;
  wire wb_req;
  output wbm_ack_o;
  input [31:0] wbm_adr_i;
  input wbm_clk_i;
  input wbm_cyc_i;
  input [31:0] wbm_dat_i;
  output [31:0] wbm_dat_o;
  output wbm_err_o;
  input wbm_rst_i;
  input [3:0] wbm_sel_i;
  input wbm_stb_i;
  input wbm_we_i;
  sky130_fd_sc_hd__inv_2 _0554_ (
    .A(wb_req),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__inv_2 _0555_ (
    .A(wbm_we_i),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__or3b_2 _0556_ (
    .A(wbm_adr_i[3]),
    .B(wbm_adr_i[4]),
    .C_N(wbm_adr_i[2]),
    .X(_0198_)
  );
  sky130_fd_sc_hd__or3_2 _0557_ (
    .A(_0196_),
    .B(_0197_),
    .C(_0198_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__buf_1 _0558_ (
    .A(_0199_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__buf_1 _0559_ (
    .A(_0200_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__inv_2 _0560_ (
    .A(_0199_),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__buf_1 _0561_ (
    .A(_0202_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__buf_1 _0562_ (
    .A(_0203_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__a22o_2 _0563_ (
    .A1(\reg_1[31] ),
    .A2(_0201_),
    .B1(wbm_dat_i[31]),
    .B2(_0204_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__inv_2 _0564_ (
    .A(wbm_rst_i),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__buf_1 _0565_ (
    .A(_0205_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__buf_1 _0566_ (
    .A(_0206_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__a22o_2 _0567_ (
    .A1(\reg_1[30] ),
    .A2(_0201_),
    .B1(wbm_dat_i[30]),
    .B2(_0204_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__buf_1 _0568_ (
    .A(_0009_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__buf_1 _0569_ (
    .A(_0207_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__a22o_2 _0570_ (
    .A1(\reg_1[29] ),
    .A2(_0201_),
    .B1(wbm_dat_i[29]),
    .B2(_0204_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__buf_1 _0571_ (
    .A(_0009_),
    .X(_0208_)
  );
  sky130_fd_sc_hd__buf_1 _0572_ (
    .A(_0208_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__a22o_2 _0573_ (
    .A1(\reg_1[28] ),
    .A2(_0201_),
    .B1(wbm_dat_i[28]),
    .B2(_0204_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__buf_1 _0574_ (
    .A(_0009_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__buf_1 _0575_ (
    .A(_0209_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__buf_1 _0576_ (
    .A(_0200_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__buf_1 _0577_ (
    .A(_0203_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__a22o_2 _0578_ (
    .A1(\reg_1[27] ),
    .A2(_0210_),
    .B1(wbm_dat_i[27]),
    .B2(_0211_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__buf_1 _0579_ (
    .A(_0206_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__buf_1 _0580_ (
    .A(_0212_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__buf_1 _0581_ (
    .A(_0213_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__buf_1 _0582_ (
    .A(_0214_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__a22o_2 _0583_ (
    .A1(\reg_1[26] ),
    .A2(_0210_),
    .B1(wbm_dat_i[26]),
    .B2(_0211_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__buf_1 _0584_ (
    .A(_0213_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__buf_1 _0585_ (
    .A(_0215_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__a22o_2 _0586_ (
    .A1(\reg_1[25] ),
    .A2(_0210_),
    .B1(wbm_dat_i[25]),
    .B2(_0211_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__buf_1 _0587_ (
    .A(_0213_),
    .X(_0216_)
  );
  sky130_fd_sc_hd__buf_1 _0588_ (
    .A(_0216_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__a22o_2 _0589_ (
    .A1(\reg_1[24] ),
    .A2(_0210_),
    .B1(wbm_dat_i[24]),
    .B2(_0211_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__buf_1 _0590_ (
    .A(_0213_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__buf_1 _0591_ (
    .A(_0217_),
    .X(_0002_)
  );
  sky130_fd_sc_hd__buf_1 _0592_ (
    .A(_0200_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__buf_1 _0593_ (
    .A(_0203_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__a22o_2 _0594_ (
    .A1(\reg_1[23] ),
    .A2(_0218_),
    .B1(wbm_dat_i[23]),
    .B2(_0219_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__buf_1 _0595_ (
    .A(_0212_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__buf_1 _0596_ (
    .A(_0220_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__buf_1 _0597_ (
    .A(_0221_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__a22o_2 _0598_ (
    .A1(\reg_1[22] ),
    .A2(_0218_),
    .B1(wbm_dat_i[22]),
    .B2(_0219_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__buf_1 _0599_ (
    .A(_0220_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__buf_1 _0600_ (
    .A(_0222_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__a22o_2 _0601_ (
    .A1(\reg_1[21] ),
    .A2(_0218_),
    .B1(wbm_dat_i[21]),
    .B2(_0219_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__buf_1 _0602_ (
    .A(_0220_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__buf_1 _0603_ (
    .A(_0223_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__a22o_2 _0604_ (
    .A1(\reg_1[20] ),
    .A2(_0218_),
    .B1(wbm_dat_i[20]),
    .B2(_0219_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__buf_1 _0605_ (
    .A(_0220_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__buf_1 _0606_ (
    .A(_0224_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__buf_1 _0607_ (
    .A(_0200_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__buf_1 _0608_ (
    .A(_0203_),
    .X(_0226_)
  );
  sky130_fd_sc_hd__a22o_2 _0609_ (
    .A1(\reg_1[19] ),
    .A2(_0225_),
    .B1(wbm_dat_i[19]),
    .B2(_0226_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__buf_1 _0610_ (
    .A(_0206_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__buf_1 _0611_ (
    .A(_0227_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__buf_1 _0612_ (
    .A(_0228_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__buf_1 _0613_ (
    .A(_0229_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__a22o_2 _0614_ (
    .A1(\reg_1[18] ),
    .A2(_0225_),
    .B1(wbm_dat_i[18]),
    .B2(_0226_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__buf_1 _0615_ (
    .A(_0228_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__buf_1 _0616_ (
    .A(_0230_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__a22o_2 _0617_ (
    .A1(\reg_1[17] ),
    .A2(_0225_),
    .B1(wbm_dat_i[17]),
    .B2(_0226_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__buf_1 _0618_ (
    .A(_0228_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__buf_1 _0619_ (
    .A(_0231_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__a22o_2 _0620_ (
    .A1(\reg_1[16] ),
    .A2(_0225_),
    .B1(wbm_dat_i[16]),
    .B2(_0226_),
    .X(_0189_)
  );
  sky130_fd_sc_hd__buf_1 _0621_ (
    .A(_0228_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__buf_1 _0622_ (
    .A(_0232_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__buf_1 _0623_ (
    .A(_0199_),
    .X(_0233_)
  );
  sky130_fd_sc_hd__buf_1 _0624_ (
    .A(_0233_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__buf_1 _0625_ (
    .A(_0202_),
    .X(_0235_)
  );
  sky130_fd_sc_hd__buf_1 _0626_ (
    .A(_0235_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__a22o_2 _0627_ (
    .A1(\reg_1[15] ),
    .A2(_0234_),
    .B1(wbm_dat_i[15]),
    .B2(_0236_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__buf_1 _0628_ (
    .A(_0227_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__buf_1 _0629_ (
    .A(_0237_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__buf_1 _0630_ (
    .A(_0238_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__a22o_2 _0631_ (
    .A1(\reg_1[14] ),
    .A2(_0234_),
    .B1(wbm_dat_i[14]),
    .B2(_0236_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__buf_1 _0632_ (
    .A(_0237_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__buf_1 _0633_ (
    .A(_0239_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__a22o_2 _0634_ (
    .A1(\reg_1[13] ),
    .A2(_0234_),
    .B1(wbm_dat_i[13]),
    .B2(_0236_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__buf_1 _0635_ (
    .A(_0237_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__buf_1 _0636_ (
    .A(_0240_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__a22o_2 _0637_ (
    .A1(\reg_1[12] ),
    .A2(_0234_),
    .B1(wbm_dat_i[12]),
    .B2(_0236_),
    .X(_0185_)
  );
  sky130_fd_sc_hd__buf_1 _0638_ (
    .A(_0237_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__buf_1 _0639_ (
    .A(_0241_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__buf_1 _0640_ (
    .A(_0233_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__buf_1 _0641_ (
    .A(_0235_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__a22o_2 _0642_ (
    .A1(\reg_1[11] ),
    .A2(_0242_),
    .B1(wbm_dat_i[11]),
    .B2(_0243_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__buf_1 _0643_ (
    .A(_0227_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__buf_1 _0644_ (
    .A(_0244_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__buf_1 _0645_ (
    .A(_0245_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__a22o_2 _0646_ (
    .A1(\reg_1[10] ),
    .A2(_0242_),
    .B1(wbm_dat_i[10]),
    .B2(_0243_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__buf_1 _0647_ (
    .A(_0244_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__buf_1 _0648_ (
    .A(_0246_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__a22o_2 _0649_ (
    .A1(\reg_1[9] ),
    .A2(_0242_),
    .B1(wbm_dat_i[9]),
    .B2(_0243_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__buf_1 _0650_ (
    .A(_0244_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__buf_1 _0651_ (
    .A(_0247_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__a22o_2 _0652_ (
    .A1(\reg_1[8] ),
    .A2(_0242_),
    .B1(wbm_dat_i[8]),
    .B2(_0243_),
    .X(_0181_)
  );
  sky130_fd_sc_hd__buf_1 _0653_ (
    .A(_0244_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__buf_1 _0654_ (
    .A(_0248_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__buf_1 _0655_ (
    .A(_0233_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__buf_1 _0656_ (
    .A(_0235_),
    .X(_0250_)
  );
  sky130_fd_sc_hd__a22o_2 _0657_ (
    .A1(\reg_1[7] ),
    .A2(_0249_),
    .B1(wbm_dat_i[7]),
    .B2(_0250_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__buf_1 _0658_ (
    .A(_0227_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__buf_1 _0659_ (
    .A(_0251_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__buf_1 _0660_ (
    .A(_0252_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__a22o_2 _0661_ (
    .A1(\reg_1[6] ),
    .A2(_0249_),
    .B1(wbm_dat_i[6]),
    .B2(_0250_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__buf_1 _0662_ (
    .A(_0251_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__buf_1 _0663_ (
    .A(_0253_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__a22o_2 _0664_ (
    .A1(\reg_1[5] ),
    .A2(_0249_),
    .B1(wbm_dat_i[5]),
    .B2(_0250_),
    .X(_0178_)
  );
  sky130_fd_sc_hd__buf_1 _0665_ (
    .A(_0251_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__buf_1 _0666_ (
    .A(_0254_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__a22o_2 _0667_ (
    .A1(\reg_1[4] ),
    .A2(_0249_),
    .B1(wbm_dat_i[4]),
    .B2(_0250_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__buf_1 _0668_ (
    .A(_0251_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__buf_1 _0669_ (
    .A(_0255_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__buf_1 _0670_ (
    .A(_0233_),
    .X(_0256_)
  );
  sky130_fd_sc_hd__buf_1 _0671_ (
    .A(_0235_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__a22o_2 _0672_ (
    .A1(\reg_1[3] ),
    .A2(_0256_),
    .B1(wbm_dat_i[3]),
    .B2(_0257_),
    .X(_0176_)
  );
  sky130_fd_sc_hd__buf_1 _0673_ (
    .A(_0205_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__buf_1 _0674_ (
    .A(_0258_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__buf_1 _0675_ (
    .A(_0259_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__buf_1 _0676_ (
    .A(_0260_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__buf_1 _0677_ (
    .A(_0261_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__a22o_2 _0678_ (
    .A1(\reg_1[2] ),
    .A2(_0256_),
    .B1(wbm_dat_i[2]),
    .B2(_0257_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__buf_1 _0679_ (
    .A(_0260_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__buf_1 _0680_ (
    .A(_0262_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__a22o_2 _0681_ (
    .A1(\reg_1[1] ),
    .A2(_0256_),
    .B1(wbm_dat_i[1]),
    .B2(_0257_),
    .X(_0174_)
  );
  sky130_fd_sc_hd__buf_1 _0682_ (
    .A(_0260_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__buf_1 _0683_ (
    .A(_0263_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__a22o_2 _0684_ (
    .A1(\reg_1[0] ),
    .A2(_0256_),
    .B1(wbm_dat_i[0]),
    .B2(_0257_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__buf_1 _0685_ (
    .A(_0260_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__buf_1 _0686_ (
    .A(_0264_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__or3_2 _0687_ (
    .A(wbm_adr_i[3]),
    .B(wbm_adr_i[2]),
    .C(wbm_adr_i[4]),
    .X(_0265_)
  );
  sky130_fd_sc_hd__or3_2 _0688_ (
    .A(_0196_),
    .B(_0197_),
    .C(_0265_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__buf_1 _0689_ (
    .A(_0266_),
    .X(_0267_)
  );
  sky130_fd_sc_hd__buf_1 _0690_ (
    .A(_0267_),
    .X(_0268_)
  );
  sky130_fd_sc_hd__inv_2 _0691_ (
    .A(_0266_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__buf_1 _0692_ (
    .A(_0269_),
    .X(_0270_)
  );
  sky130_fd_sc_hd__buf_1 _0693_ (
    .A(_0270_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__a22o_2 _0694_ (
    .A1(\reg_0[31] ),
    .A2(_0268_),
    .B1(wbm_dat_i[31]),
    .B2(_0271_),
    .X(_0172_)
  );
  sky130_fd_sc_hd__buf_1 _0695_ (
    .A(_0259_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__buf_1 _0696_ (
    .A(_0272_),
    .X(_0273_)
  );
  sky130_fd_sc_hd__buf_1 _0697_ (
    .A(_0273_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__a22o_2 _0698_ (
    .A1(\reg_0[30] ),
    .A2(_0268_),
    .B1(wbm_dat_i[30]),
    .B2(_0271_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__buf_1 _0699_ (
    .A(_0272_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__buf_1 _0700_ (
    .A(_0274_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__a22o_2 _0701_ (
    .A1(\reg_0[29] ),
    .A2(_0268_),
    .B1(wbm_dat_i[29]),
    .B2(_0271_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__buf_1 _0702_ (
    .A(_0272_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__buf_1 _0703_ (
    .A(_0275_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__a22o_2 _0704_ (
    .A1(\reg_0[28] ),
    .A2(_0268_),
    .B1(wbm_dat_i[28]),
    .B2(_0271_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__buf_1 _0705_ (
    .A(_0272_),
    .X(_0276_)
  );
  sky130_fd_sc_hd__buf_1 _0706_ (
    .A(_0276_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__buf_1 _0707_ (
    .A(_0267_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__buf_1 _0708_ (
    .A(_0270_),
    .X(_0278_)
  );
  sky130_fd_sc_hd__a22o_2 _0709_ (
    .A1(\reg_0[27] ),
    .A2(_0277_),
    .B1(wbm_dat_i[27]),
    .B2(_0278_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__buf_1 _0710_ (
    .A(_0259_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__buf_1 _0711_ (
    .A(_0279_),
    .X(_0280_)
  );
  sky130_fd_sc_hd__buf_1 _0712_ (
    .A(_0280_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__a22o_2 _0713_ (
    .A1(\reg_0[26] ),
    .A2(_0277_),
    .B1(wbm_dat_i[26]),
    .B2(_0278_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__buf_1 _0714_ (
    .A(_0279_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__buf_1 _0715_ (
    .A(_0281_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__a22o_2 _0716_ (
    .A1(\reg_0[25] ),
    .A2(_0277_),
    .B1(wbm_dat_i[25]),
    .B2(_0278_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__buf_1 _0717_ (
    .A(_0279_),
    .X(_0282_)
  );
  sky130_fd_sc_hd__buf_1 _0718_ (
    .A(_0282_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__a22o_2 _0719_ (
    .A1(\reg_0[24] ),
    .A2(_0277_),
    .B1(wbm_dat_i[24]),
    .B2(_0278_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__buf_1 _0720_ (
    .A(_0279_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__buf_1 _0721_ (
    .A(_0283_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__buf_1 _0722_ (
    .A(_0267_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__buf_1 _0723_ (
    .A(_0270_),
    .X(_0285_)
  );
  sky130_fd_sc_hd__a22o_2 _0724_ (
    .A1(\reg_0[23] ),
    .A2(_0284_),
    .B1(wbm_dat_i[23]),
    .B2(_0285_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__buf_1 _0725_ (
    .A(_0259_),
    .X(_0286_)
  );
  sky130_fd_sc_hd__buf_1 _0726_ (
    .A(_0286_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__buf_1 _0727_ (
    .A(_0287_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__a22o_2 _0728_ (
    .A1(\reg_0[22] ),
    .A2(_0284_),
    .B1(wbm_dat_i[22]),
    .B2(_0285_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__buf_1 _0729_ (
    .A(_0286_),
    .X(_0288_)
  );
  sky130_fd_sc_hd__buf_1 _0730_ (
    .A(_0288_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__a22o_2 _0731_ (
    .A1(\reg_0[21] ),
    .A2(_0284_),
    .B1(wbm_dat_i[21]),
    .B2(_0285_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__buf_1 _0732_ (
    .A(_0286_),
    .X(_0289_)
  );
  sky130_fd_sc_hd__buf_1 _0733_ (
    .A(_0289_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__a22o_2 _0734_ (
    .A1(\reg_0[20] ),
    .A2(_0284_),
    .B1(wbm_dat_i[20]),
    .B2(_0285_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__buf_1 _0735_ (
    .A(_0286_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__buf_1 _0736_ (
    .A(_0290_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__buf_1 _0737_ (
    .A(_0267_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__buf_1 _0738_ (
    .A(_0270_),
    .X(_0292_)
  );
  sky130_fd_sc_hd__a22o_2 _0739_ (
    .A1(\reg_0[19] ),
    .A2(_0291_),
    .B1(wbm_dat_i[19]),
    .B2(_0292_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__buf_1 _0740_ (
    .A(_0258_),
    .X(_0293_)
  );
  sky130_fd_sc_hd__buf_1 _0741_ (
    .A(_0293_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__buf_1 _0742_ (
    .A(_0294_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__buf_1 _0743_ (
    .A(_0295_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__a22o_2 _0744_ (
    .A1(\reg_0[18] ),
    .A2(_0291_),
    .B1(wbm_dat_i[18]),
    .B2(_0292_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__buf_1 _0745_ (
    .A(_0294_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__buf_1 _0746_ (
    .A(_0296_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__a22o_2 _0747_ (
    .A1(\reg_0[17] ),
    .A2(_0291_),
    .B1(wbm_dat_i[17]),
    .B2(_0292_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__buf_1 _0748_ (
    .A(_0294_),
    .X(_0297_)
  );
  sky130_fd_sc_hd__buf_1 _0749_ (
    .A(_0297_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__a22o_2 _0750_ (
    .A1(\reg_0[16] ),
    .A2(_0291_),
    .B1(wbm_dat_i[16]),
    .B2(_0292_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__buf_1 _0751_ (
    .A(_0294_),
    .X(_0298_)
  );
  sky130_fd_sc_hd__buf_1 _0752_ (
    .A(_0298_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__buf_1 _0753_ (
    .A(_0266_),
    .X(_0299_)
  );
  sky130_fd_sc_hd__buf_1 _0754_ (
    .A(_0299_),
    .X(_0300_)
  );
  sky130_fd_sc_hd__buf_1 _0755_ (
    .A(_0269_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__buf_1 _0756_ (
    .A(_0301_),
    .X(_0302_)
  );
  sky130_fd_sc_hd__a22o_2 _0757_ (
    .A1(\reg_0[15] ),
    .A2(_0300_),
    .B1(wbm_dat_i[15]),
    .B2(_0302_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__buf_1 _0758_ (
    .A(_0293_),
    .X(_0303_)
  );
  sky130_fd_sc_hd__buf_1 _0759_ (
    .A(_0303_),
    .X(_0304_)
  );
  sky130_fd_sc_hd__buf_1 _0760_ (
    .A(_0304_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__a22o_2 _0761_ (
    .A1(\reg_0[14] ),
    .A2(_0300_),
    .B1(wbm_dat_i[14]),
    .B2(_0302_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__buf_1 _0762_ (
    .A(_0303_),
    .X(_0305_)
  );
  sky130_fd_sc_hd__buf_1 _0763_ (
    .A(_0305_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__a22o_2 _0764_ (
    .A1(\reg_0[13] ),
    .A2(_0300_),
    .B1(wbm_dat_i[13]),
    .B2(_0302_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__buf_1 _0765_ (
    .A(_0303_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__buf_1 _0766_ (
    .A(_0306_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__a22o_2 _0767_ (
    .A1(\reg_0[12] ),
    .A2(_0300_),
    .B1(wbm_dat_i[12]),
    .B2(_0302_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__buf_1 _0768_ (
    .A(_0303_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__buf_1 _0769_ (
    .A(_0307_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__buf_1 _0770_ (
    .A(_0299_),
    .X(_0308_)
  );
  sky130_fd_sc_hd__buf_1 _0771_ (
    .A(_0301_),
    .X(_0309_)
  );
  sky130_fd_sc_hd__a22o_2 _0772_ (
    .A1(\reg_0[11] ),
    .A2(_0308_),
    .B1(wbm_dat_i[11]),
    .B2(_0309_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__buf_1 _0773_ (
    .A(_0293_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__buf_1 _0774_ (
    .A(_0310_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__buf_1 _0775_ (
    .A(_0311_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__a22o_2 _0776_ (
    .A1(\reg_0[10] ),
    .A2(_0308_),
    .B1(wbm_dat_i[10]),
    .B2(_0309_),
    .X(_0151_)
  );
  sky130_fd_sc_hd__buf_1 _0777_ (
    .A(_0310_),
    .X(_0312_)
  );
  sky130_fd_sc_hd__buf_1 _0778_ (
    .A(_0312_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__a22o_2 _0779_ (
    .A1(\reg_0[9] ),
    .A2(_0308_),
    .B1(wbm_dat_i[9]),
    .B2(_0309_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__buf_1 _0780_ (
    .A(_0310_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__buf_1 _0781_ (
    .A(_0313_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__a22o_2 _0782_ (
    .A1(\reg_0[8] ),
    .A2(_0308_),
    .B1(wbm_dat_i[8]),
    .B2(_0309_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__buf_1 _0783_ (
    .A(_0310_),
    .X(_0314_)
  );
  sky130_fd_sc_hd__buf_1 _0784_ (
    .A(_0314_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__buf_1 _0785_ (
    .A(_0299_),
    .X(_0315_)
  );
  sky130_fd_sc_hd__buf_1 _0786_ (
    .A(_0301_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__a22o_2 _0787_ (
    .A1(\reg_0[7] ),
    .A2(_0315_),
    .B1(wbm_dat_i[7]),
    .B2(_0316_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__buf_1 _0788_ (
    .A(_0293_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__buf_1 _0789_ (
    .A(_0317_),
    .X(_0318_)
  );
  sky130_fd_sc_hd__buf_1 _0790_ (
    .A(_0318_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__a22o_2 _0791_ (
    .A1(\reg_0[6] ),
    .A2(_0315_),
    .B1(wbm_dat_i[6]),
    .B2(_0316_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__buf_1 _0792_ (
    .A(_0317_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__buf_1 _0793_ (
    .A(_0319_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__a22o_2 _0794_ (
    .A1(\reg_0[5] ),
    .A2(_0315_),
    .B1(wbm_dat_i[5]),
    .B2(_0316_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__buf_1 _0795_ (
    .A(_0317_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__buf_1 _0796_ (
    .A(_0320_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__a22o_2 _0797_ (
    .A1(\reg_0[4] ),
    .A2(_0315_),
    .B1(wbm_dat_i[4]),
    .B2(_0316_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__buf_1 _0798_ (
    .A(_0317_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__buf_1 _0799_ (
    .A(_0321_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__buf_1 _0800_ (
    .A(_0299_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__buf_1 _0801_ (
    .A(_0301_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__a22o_2 _0802_ (
    .A1(\reg_0[3] ),
    .A2(_0322_),
    .B1(wbm_dat_i[3]),
    .B2(_0323_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__buf_1 _0803_ (
    .A(_0258_),
    .X(_0324_)
  );
  sky130_fd_sc_hd__buf_1 _0804_ (
    .A(_0324_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__buf_1 _0805_ (
    .A(_0325_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__buf_1 _0806_ (
    .A(_0326_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__a22o_2 _0807_ (
    .A1(\reg_0[2] ),
    .A2(_0322_),
    .B1(wbm_dat_i[2]),
    .B2(_0323_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__buf_1 _0808_ (
    .A(_0325_),
    .X(_0327_)
  );
  sky130_fd_sc_hd__buf_1 _0809_ (
    .A(_0327_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__a22o_2 _0810_ (
    .A1(\reg_0[1] ),
    .A2(_0322_),
    .B1(wbm_dat_i[1]),
    .B2(_0323_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__buf_1 _0811_ (
    .A(_0325_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__buf_1 _0812_ (
    .A(_0328_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__a22o_2 _0813_ (
    .A1(\reg_0[0] ),
    .A2(_0322_),
    .B1(wbm_dat_i[0]),
    .B2(_0323_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__buf_1 _0814_ (
    .A(_0325_),
    .X(_0329_)
  );
  sky130_fd_sc_hd__buf_1 _0815_ (
    .A(_0329_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__or2_2 _0816_ (
    .A(_0196_),
    .B(reg_ack),
    .X(_0330_)
  );
  sky130_fd_sc_hd__inv_2 _0817_ (
    .A(_0330_),
    .Y(_0331_)
  );
  sky130_fd_sc_hd__buf_1 _0818_ (
    .A(_0331_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__inv_2 _0819_ (
    .A(\reg_rdata[31] ),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__buf_1 _0820_ (
    .A(_0330_),
    .X(_0333_)
  );
  sky130_fd_sc_hd__buf_1 _0821_ (
    .A(_0333_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__inv_2 _0822_ (
    .A(\reg_1[31] ),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__buf_1 _0823_ (
    .A(_0198_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__buf_1 _0824_ (
    .A(_0336_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__inv_2 _0825_ (
    .A(\reg_0[31] ),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__buf_1 _0826_ (
    .A(_0265_),
    .X(_0339_)
  );
  sky130_fd_sc_hd__buf_1 _0827_ (
    .A(_0339_),
    .X(_0340_)
  );
  sky130_fd_sc_hd__o22a_2 _0828_ (
    .A1(_0335_),
    .A2(_0337_),
    .B1(_0338_),
    .B2(_0340_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__o22ai_2 _0829_ (
    .A1(_0332_),
    .A2(_0000_),
    .B1(_0334_),
    .B2(_0341_),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__buf_1 _0830_ (
    .A(_0324_),
    .X(_0342_)
  );
  sky130_fd_sc_hd__buf_1 _0831_ (
    .A(_0342_),
    .X(_0343_)
  );
  sky130_fd_sc_hd__buf_1 _0832_ (
    .A(_0343_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__inv_2 _0833_ (
    .A(\reg_rdata[30] ),
    .Y(_0344_)
  );
  sky130_fd_sc_hd__inv_2 _0834_ (
    .A(\reg_1[30] ),
    .Y(_0345_)
  );
  sky130_fd_sc_hd__inv_2 _0835_ (
    .A(\reg_0[30] ),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__o22a_2 _0836_ (
    .A1(_0345_),
    .A2(_0337_),
    .B1(_0346_),
    .B2(_0340_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__o22ai_2 _0837_ (
    .A1(_0344_),
    .A2(_0000_),
    .B1(_0334_),
    .B2(_0347_),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__buf_1 _0838_ (
    .A(_0342_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__buf_1 _0839_ (
    .A(_0348_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__inv_2 _0840_ (
    .A(\reg_rdata[29] ),
    .Y(_0349_)
  );
  sky130_fd_sc_hd__inv_2 _0841_ (
    .A(\reg_1[29] ),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__inv_2 _0842_ (
    .A(\reg_0[29] ),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__o22a_2 _0843_ (
    .A1(_0350_),
    .A2(_0337_),
    .B1(_0351_),
    .B2(_0340_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__o22ai_2 _0844_ (
    .A1(_0349_),
    .A2(_0000_),
    .B1(_0334_),
    .B2(_0352_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__buf_1 _0845_ (
    .A(_0342_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__buf_1 _0846_ (
    .A(_0353_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__inv_2 _0847_ (
    .A(\reg_rdata[28] ),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__buf_1 _0848_ (
    .A(_0331_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__buf_1 _0849_ (
    .A(_0355_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__inv_2 _0850_ (
    .A(\reg_1[28] ),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__buf_1 _0851_ (
    .A(_0336_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__inv_2 _0852_ (
    .A(\reg_0[28] ),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__o22a_2 _0853_ (
    .A1(_0357_),
    .A2(_0358_),
    .B1(_0359_),
    .B2(_0340_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__o22ai_2 _0854_ (
    .A1(_0354_),
    .A2(_0356_),
    .B1(_0334_),
    .B2(_0360_),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__buf_1 _0855_ (
    .A(_0342_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__buf_1 _0856_ (
    .A(_0361_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__inv_2 _0857_ (
    .A(\reg_rdata[27] ),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__buf_1 _0858_ (
    .A(_0333_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__inv_2 _0859_ (
    .A(\reg_1[27] ),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__inv_2 _0860_ (
    .A(\reg_0[27] ),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__buf_1 _0861_ (
    .A(_0339_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__o22a_2 _0862_ (
    .A1(_0364_),
    .A2(_0358_),
    .B1(_0365_),
    .B2(_0366_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__o22ai_2 _0863_ (
    .A1(_0362_),
    .A2(_0356_),
    .B1(_0363_),
    .B2(_0367_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__buf_1 _0864_ (
    .A(_0324_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__buf_1 _0865_ (
    .A(_0368_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__buf_1 _0866_ (
    .A(_0369_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__inv_2 _0867_ (
    .A(\reg_rdata[26] ),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__inv_2 _0868_ (
    .A(\reg_1[26] ),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__inv_2 _0869_ (
    .A(\reg_0[26] ),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__o22a_2 _0870_ (
    .A1(_0371_),
    .A2(_0358_),
    .B1(_0372_),
    .B2(_0366_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__o22ai_2 _0871_ (
    .A1(_0370_),
    .A2(_0356_),
    .B1(_0363_),
    .B2(_0373_),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__buf_1 _0872_ (
    .A(_0368_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__buf_1 _0873_ (
    .A(_0374_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__inv_2 _0874_ (
    .A(\reg_rdata[25] ),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__inv_2 _0875_ (
    .A(\reg_1[25] ),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__inv_2 _0876_ (
    .A(\reg_0[25] ),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__o22a_2 _0877_ (
    .A1(_0376_),
    .A2(_0358_),
    .B1(_0377_),
    .B2(_0366_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__o22ai_2 _0878_ (
    .A1(_0375_),
    .A2(_0356_),
    .B1(_0363_),
    .B2(_0378_),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__buf_1 _0879_ (
    .A(_0368_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__buf_1 _0880_ (
    .A(_0379_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__inv_2 _0881_ (
    .A(\reg_rdata[24] ),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__buf_1 _0882_ (
    .A(_0355_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__inv_2 _0883_ (
    .A(\reg_1[24] ),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__buf_1 _0884_ (
    .A(_0336_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__inv_2 _0885_ (
    .A(\reg_0[24] ),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__o22a_2 _0886_ (
    .A1(_0382_),
    .A2(_0383_),
    .B1(_0384_),
    .B2(_0366_),
    .X(_0385_)
  );
  sky130_fd_sc_hd__o22ai_2 _0887_ (
    .A1(_0380_),
    .A2(_0381_),
    .B1(_0363_),
    .B2(_0385_),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__buf_1 _0888_ (
    .A(_0368_),
    .X(_0386_)
  );
  sky130_fd_sc_hd__buf_1 _0889_ (
    .A(_0386_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__inv_2 _0890_ (
    .A(\reg_rdata[23] ),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__buf_1 _0891_ (
    .A(_0333_),
    .X(_0388_)
  );
  sky130_fd_sc_hd__inv_2 _0892_ (
    .A(\reg_1[23] ),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__inv_2 _0893_ (
    .A(\reg_0[23] ),
    .Y(_0390_)
  );
  sky130_fd_sc_hd__buf_1 _0894_ (
    .A(_0339_),
    .X(_0391_)
  );
  sky130_fd_sc_hd__o22a_2 _0895_ (
    .A1(_0389_),
    .A2(_0383_),
    .B1(_0390_),
    .B2(_0391_),
    .X(_0392_)
  );
  sky130_fd_sc_hd__o22ai_2 _0896_ (
    .A1(_0387_),
    .A2(_0381_),
    .B1(_0388_),
    .B2(_0392_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__buf_1 _0897_ (
    .A(_0324_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__buf_1 _0898_ (
    .A(_0393_),
    .X(_0394_)
  );
  sky130_fd_sc_hd__buf_1 _0899_ (
    .A(_0394_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__inv_2 _0900_ (
    .A(\reg_rdata[22] ),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__inv_2 _0901_ (
    .A(\reg_1[22] ),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__inv_2 _0902_ (
    .A(\reg_0[22] ),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__o22a_2 _0903_ (
    .A1(_0396_),
    .A2(_0383_),
    .B1(_0397_),
    .B2(_0391_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__o22ai_2 _0904_ (
    .A1(_0395_),
    .A2(_0381_),
    .B1(_0388_),
    .B2(_0398_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__buf_1 _0905_ (
    .A(_0393_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__buf_1 _0906_ (
    .A(_0399_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__inv_2 _0907_ (
    .A(\reg_rdata[21] ),
    .Y(_0400_)
  );
  sky130_fd_sc_hd__inv_2 _0908_ (
    .A(\reg_1[21] ),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__inv_2 _0909_ (
    .A(\reg_0[21] ),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__o22a_2 _0910_ (
    .A1(_0401_),
    .A2(_0383_),
    .B1(_0402_),
    .B2(_0391_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__o22ai_2 _0911_ (
    .A1(_0400_),
    .A2(_0381_),
    .B1(_0388_),
    .B2(_0403_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__buf_1 _0912_ (
    .A(_0393_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__buf_1 _0913_ (
    .A(_0404_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__inv_2 _0914_ (
    .A(\reg_rdata[20] ),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__buf_1 _0915_ (
    .A(_0355_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__inv_2 _0916_ (
    .A(\reg_1[20] ),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__buf_1 _0917_ (
    .A(_0336_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__inv_2 _0918_ (
    .A(\reg_0[20] ),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__o22a_2 _0919_ (
    .A1(_0407_),
    .A2(_0408_),
    .B1(_0409_),
    .B2(_0391_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__o22ai_2 _0920_ (
    .A1(_0405_),
    .A2(_0406_),
    .B1(_0388_),
    .B2(_0410_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__buf_1 _0921_ (
    .A(_0393_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__buf_1 _0922_ (
    .A(_0411_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__inv_2 _0923_ (
    .A(\reg_rdata[19] ),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__buf_1 _0924_ (
    .A(_0333_),
    .X(_0413_)
  );
  sky130_fd_sc_hd__inv_2 _0925_ (
    .A(\reg_1[19] ),
    .Y(_0414_)
  );
  sky130_fd_sc_hd__inv_2 _0926_ (
    .A(\reg_0[19] ),
    .Y(_0415_)
  );
  sky130_fd_sc_hd__buf_1 _0927_ (
    .A(_0339_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__o22a_2 _0928_ (
    .A1(_0414_),
    .A2(_0408_),
    .B1(_0415_),
    .B2(_0416_),
    .X(_0417_)
  );
  sky130_fd_sc_hd__o22ai_2 _0929_ (
    .A1(_0412_),
    .A2(_0406_),
    .B1(_0413_),
    .B2(_0417_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__buf_1 _0930_ (
    .A(_0258_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__buf_1 _0931_ (
    .A(_0418_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__buf_1 _0932_ (
    .A(_0419_),
    .X(_0420_)
  );
  sky130_fd_sc_hd__buf_1 _0933_ (
    .A(_0420_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__inv_2 _0934_ (
    .A(\reg_rdata[18] ),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__inv_2 _0935_ (
    .A(\reg_1[18] ),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__inv_2 _0936_ (
    .A(\reg_0[18] ),
    .Y(_0423_)
  );
  sky130_fd_sc_hd__o22a_2 _0937_ (
    .A1(_0422_),
    .A2(_0408_),
    .B1(_0423_),
    .B2(_0416_),
    .X(_0424_)
  );
  sky130_fd_sc_hd__o22ai_2 _0938_ (
    .A1(_0421_),
    .A2(_0406_),
    .B1(_0413_),
    .B2(_0424_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__buf_1 _0939_ (
    .A(_0419_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__buf_1 _0940_ (
    .A(_0425_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__inv_2 _0941_ (
    .A(\reg_rdata[17] ),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__inv_2 _0942_ (
    .A(\reg_1[17] ),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__inv_2 _0943_ (
    .A(\reg_0[17] ),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__o22a_2 _0944_ (
    .A1(_0427_),
    .A2(_0408_),
    .B1(_0428_),
    .B2(_0416_),
    .X(_0429_)
  );
  sky130_fd_sc_hd__o22ai_2 _0945_ (
    .A1(_0426_),
    .A2(_0406_),
    .B1(_0413_),
    .B2(_0429_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__buf_1 _0946_ (
    .A(_0419_),
    .X(_0430_)
  );
  sky130_fd_sc_hd__buf_1 _0947_ (
    .A(_0430_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__inv_2 _0948_ (
    .A(\reg_rdata[16] ),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__buf_1 _0949_ (
    .A(_0331_),
    .X(_0432_)
  );
  sky130_fd_sc_hd__buf_1 _0950_ (
    .A(_0432_),
    .X(_0433_)
  );
  sky130_fd_sc_hd__inv_2 _0951_ (
    .A(\reg_1[16] ),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__buf_1 _0952_ (
    .A(_0198_),
    .X(_0435_)
  );
  sky130_fd_sc_hd__buf_1 _0953_ (
    .A(_0435_),
    .X(_0436_)
  );
  sky130_fd_sc_hd__inv_2 _0954_ (
    .A(\reg_0[16] ),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__o22a_2 _0955_ (
    .A1(_0434_),
    .A2(_0436_),
    .B1(_0437_),
    .B2(_0416_),
    .X(_0438_)
  );
  sky130_fd_sc_hd__o22ai_2 _0956_ (
    .A1(_0431_),
    .A2(_0433_),
    .B1(_0413_),
    .B2(_0438_),
    .Y(_0125_)
  );
  sky130_fd_sc_hd__buf_1 _0957_ (
    .A(_0419_),
    .X(_0439_)
  );
  sky130_fd_sc_hd__buf_1 _0958_ (
    .A(_0439_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__inv_2 _0959_ (
    .A(\reg_rdata[15] ),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__buf_1 _0960_ (
    .A(_0330_),
    .X(_0441_)
  );
  sky130_fd_sc_hd__buf_1 _0961_ (
    .A(_0441_),
    .X(_0442_)
  );
  sky130_fd_sc_hd__inv_2 _0962_ (
    .A(\reg_1[15] ),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__inv_2 _0963_ (
    .A(\reg_0[15] ),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__buf_1 _0964_ (
    .A(_0265_),
    .X(_0445_)
  );
  sky130_fd_sc_hd__buf_1 _0965_ (
    .A(_0445_),
    .X(_0446_)
  );
  sky130_fd_sc_hd__o22a_2 _0966_ (
    .A1(_0443_),
    .A2(_0436_),
    .B1(_0444_),
    .B2(_0446_),
    .X(_0447_)
  );
  sky130_fd_sc_hd__o22ai_2 _0967_ (
    .A1(_0440_),
    .A2(_0433_),
    .B1(_0442_),
    .B2(_0447_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__buf_1 _0968_ (
    .A(_0418_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__buf_1 _0969_ (
    .A(_0448_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__buf_1 _0970_ (
    .A(_0449_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__inv_2 _0971_ (
    .A(\reg_rdata[14] ),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__inv_2 _0972_ (
    .A(\reg_1[14] ),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__inv_2 _0973_ (
    .A(\reg_0[14] ),
    .Y(_0452_)
  );
  sky130_fd_sc_hd__o22a_2 _0974_ (
    .A1(_0451_),
    .A2(_0436_),
    .B1(_0452_),
    .B2(_0446_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__o22ai_2 _0975_ (
    .A1(_0450_),
    .A2(_0433_),
    .B1(_0442_),
    .B2(_0453_),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__buf_1 _0976_ (
    .A(_0448_),
    .X(_0454_)
  );
  sky130_fd_sc_hd__buf_1 _0977_ (
    .A(_0454_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__inv_2 _0978_ (
    .A(\reg_rdata[13] ),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__inv_2 _0979_ (
    .A(\reg_1[13] ),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__inv_2 _0980_ (
    .A(\reg_0[13] ),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__o22a_2 _0981_ (
    .A1(_0456_),
    .A2(_0436_),
    .B1(_0457_),
    .B2(_0446_),
    .X(_0458_)
  );
  sky130_fd_sc_hd__o22ai_2 _0982_ (
    .A1(_0455_),
    .A2(_0433_),
    .B1(_0442_),
    .B2(_0458_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__buf_1 _0983_ (
    .A(_0448_),
    .X(_0459_)
  );
  sky130_fd_sc_hd__buf_1 _0984_ (
    .A(_0459_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__inv_2 _0985_ (
    .A(\reg_rdata[12] ),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__buf_1 _0986_ (
    .A(_0432_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__inv_2 _0987_ (
    .A(\reg_1[12] ),
    .Y(_0462_)
  );
  sky130_fd_sc_hd__buf_1 _0988_ (
    .A(_0435_),
    .X(_0463_)
  );
  sky130_fd_sc_hd__inv_2 _0989_ (
    .A(\reg_0[12] ),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__o22a_2 _0990_ (
    .A1(_0462_),
    .A2(_0463_),
    .B1(_0464_),
    .B2(_0446_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__o22ai_2 _0991_ (
    .A1(_0460_),
    .A2(_0461_),
    .B1(_0442_),
    .B2(_0465_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__buf_1 _0992_ (
    .A(_0448_),
    .X(_0466_)
  );
  sky130_fd_sc_hd__buf_1 _0993_ (
    .A(_0466_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__inv_2 _0994_ (
    .A(\reg_rdata[11] ),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__buf_1 _0995_ (
    .A(_0441_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__inv_2 _0996_ (
    .A(\reg_1[11] ),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__inv_2 _0997_ (
    .A(\reg_0[11] ),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__buf_1 _0998_ (
    .A(_0445_),
    .X(_0471_)
  );
  sky130_fd_sc_hd__o22a_2 _0999_ (
    .A1(_0469_),
    .A2(_0463_),
    .B1(_0470_),
    .B2(_0471_),
    .X(_0472_)
  );
  sky130_fd_sc_hd__o22ai_2 _1000_ (
    .A1(_0467_),
    .A2(_0461_),
    .B1(_0468_),
    .B2(_0472_),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__buf_1 _1001_ (
    .A(_0418_),
    .X(_0473_)
  );
  sky130_fd_sc_hd__buf_1 _1002_ (
    .A(_0473_),
    .X(_0474_)
  );
  sky130_fd_sc_hd__buf_1 _1003_ (
    .A(_0474_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__inv_2 _1004_ (
    .A(\reg_rdata[10] ),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__inv_2 _1005_ (
    .A(\reg_1[10] ),
    .Y(_0476_)
  );
  sky130_fd_sc_hd__inv_2 _1006_ (
    .A(\reg_0[10] ),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__o22a_2 _1007_ (
    .A1(_0476_),
    .A2(_0463_),
    .B1(_0477_),
    .B2(_0471_),
    .X(_0478_)
  );
  sky130_fd_sc_hd__o22ai_2 _1008_ (
    .A1(_0475_),
    .A2(_0461_),
    .B1(_0468_),
    .B2(_0478_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__buf_1 _1009_ (
    .A(_0473_),
    .X(_0479_)
  );
  sky130_fd_sc_hd__buf_1 _1010_ (
    .A(_0479_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__inv_2 _1011_ (
    .A(\reg_rdata[9] ),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__inv_2 _1012_ (
    .A(\reg_1[9] ),
    .Y(_0481_)
  );
  sky130_fd_sc_hd__inv_2 _1013_ (
    .A(\reg_0[9] ),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__o22a_2 _1014_ (
    .A1(_0481_),
    .A2(_0463_),
    .B1(_0482_),
    .B2(_0471_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__o22ai_2 _1015_ (
    .A1(_0480_),
    .A2(_0461_),
    .B1(_0468_),
    .B2(_0483_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__buf_1 _1016_ (
    .A(_0473_),
    .X(_0484_)
  );
  sky130_fd_sc_hd__buf_1 _1017_ (
    .A(_0484_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__inv_2 _1018_ (
    .A(\reg_rdata[8] ),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__buf_1 _1019_ (
    .A(_0432_),
    .X(_0486_)
  );
  sky130_fd_sc_hd__inv_2 _1020_ (
    .A(\reg_1[8] ),
    .Y(_0487_)
  );
  sky130_fd_sc_hd__buf_1 _1021_ (
    .A(_0435_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__inv_2 _1022_ (
    .A(\reg_0[8] ),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__o22a_2 _1023_ (
    .A1(_0487_),
    .A2(_0488_),
    .B1(_0489_),
    .B2(_0471_),
    .X(_0490_)
  );
  sky130_fd_sc_hd__o22ai_2 _1024_ (
    .A1(_0485_),
    .A2(_0486_),
    .B1(_0468_),
    .B2(_0490_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__buf_1 _1025_ (
    .A(_0473_),
    .X(_0491_)
  );
  sky130_fd_sc_hd__buf_1 _1026_ (
    .A(_0491_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__inv_2 _1027_ (
    .A(\reg_rdata[7] ),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__buf_1 _1028_ (
    .A(_0441_),
    .X(_0493_)
  );
  sky130_fd_sc_hd__inv_2 _1029_ (
    .A(\reg_1[7] ),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__inv_2 _1030_ (
    .A(\reg_0[7] ),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__buf_1 _1031_ (
    .A(_0445_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__o22a_2 _1032_ (
    .A1(_0494_),
    .A2(_0488_),
    .B1(_0495_),
    .B2(_0496_),
    .X(_0497_)
  );
  sky130_fd_sc_hd__o22ai_2 _1033_ (
    .A1(_0492_),
    .A2(_0486_),
    .B1(_0493_),
    .B2(_0497_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__buf_1 _1034_ (
    .A(_0418_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__buf_1 _1035_ (
    .A(_0498_),
    .X(_0499_)
  );
  sky130_fd_sc_hd__buf_1 _1036_ (
    .A(_0499_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__inv_2 _1037_ (
    .A(\reg_rdata[6] ),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__inv_2 _1038_ (
    .A(\reg_1[6] ),
    .Y(_0501_)
  );
  sky130_fd_sc_hd__inv_2 _1039_ (
    .A(\reg_0[6] ),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__o22a_2 _1040_ (
    .A1(_0501_),
    .A2(_0488_),
    .B1(_0502_),
    .B2(_0496_),
    .X(_0503_)
  );
  sky130_fd_sc_hd__o22ai_2 _1041_ (
    .A1(_0500_),
    .A2(_0486_),
    .B1(_0493_),
    .B2(_0503_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__buf_1 _1042_ (
    .A(_0498_),
    .X(_0504_)
  );
  sky130_fd_sc_hd__buf_1 _1043_ (
    .A(_0504_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__inv_2 _1044_ (
    .A(\reg_rdata[5] ),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__inv_2 _1045_ (
    .A(\reg_1[5] ),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__inv_2 _1046_ (
    .A(\reg_0[5] ),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__o22a_2 _1047_ (
    .A1(_0506_),
    .A2(_0488_),
    .B1(_0507_),
    .B2(_0496_),
    .X(_0508_)
  );
  sky130_fd_sc_hd__o22ai_2 _1048_ (
    .A1(_0505_),
    .A2(_0486_),
    .B1(_0493_),
    .B2(_0508_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__buf_1 _1049_ (
    .A(_0498_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__buf_1 _1050_ (
    .A(_0509_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__inv_2 _1051_ (
    .A(\reg_rdata[4] ),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__buf_1 _1052_ (
    .A(_0432_),
    .X(_0511_)
  );
  sky130_fd_sc_hd__inv_2 _1053_ (
    .A(\reg_1[4] ),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__buf_1 _1054_ (
    .A(_0435_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__inv_2 _1055_ (
    .A(\reg_0[4] ),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__o22a_2 _1056_ (
    .A1(_0512_),
    .A2(_0513_),
    .B1(_0514_),
    .B2(_0496_),
    .X(_0515_)
  );
  sky130_fd_sc_hd__o22ai_2 _1057_ (
    .A1(_0510_),
    .A2(_0511_),
    .B1(_0493_),
    .B2(_0515_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__buf_1 _1058_ (
    .A(_0498_),
    .X(_0516_)
  );
  sky130_fd_sc_hd__buf_1 _1059_ (
    .A(_0516_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__inv_2 _1060_ (
    .A(\reg_rdata[3] ),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__buf_1 _1061_ (
    .A(_0441_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__inv_2 _1062_ (
    .A(\reg_1[3] ),
    .Y(_0519_)
  );
  sky130_fd_sc_hd__inv_2 _1063_ (
    .A(\reg_0[3] ),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__buf_1 _1064_ (
    .A(_0445_),
    .X(_0521_)
  );
  sky130_fd_sc_hd__o22a_2 _1065_ (
    .A1(_0519_),
    .A2(_0513_),
    .B1(_0520_),
    .B2(_0521_),
    .X(_0522_)
  );
  sky130_fd_sc_hd__o22ai_2 _1066_ (
    .A1(_0517_),
    .A2(_0511_),
    .B1(_0518_),
    .B2(_0522_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__buf_1 _1067_ (
    .A(_0206_),
    .X(_0523_)
  );
  sky130_fd_sc_hd__buf_1 _1068_ (
    .A(_0523_),
    .X(_0524_)
  );
  sky130_fd_sc_hd__buf_1 _1069_ (
    .A(_0524_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__inv_2 _1070_ (
    .A(\reg_rdata[2] ),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__inv_2 _1071_ (
    .A(\reg_1[2] ),
    .Y(_0526_)
  );
  sky130_fd_sc_hd__inv_2 _1072_ (
    .A(\reg_0[2] ),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__o22a_2 _1073_ (
    .A1(_0526_),
    .A2(_0513_),
    .B1(_0527_),
    .B2(_0521_),
    .X(_0528_)
  );
  sky130_fd_sc_hd__o22ai_2 _1074_ (
    .A1(_0525_),
    .A2(_0511_),
    .B1(_0518_),
    .B2(_0528_),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__buf_1 _1075_ (
    .A(_0523_),
    .X(_0529_)
  );
  sky130_fd_sc_hd__buf_1 _1076_ (
    .A(_0529_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__inv_2 _1077_ (
    .A(\reg_rdata[1] ),
    .Y(_0530_)
  );
  sky130_fd_sc_hd__inv_2 _1078_ (
    .A(\reg_1[1] ),
    .Y(_0531_)
  );
  sky130_fd_sc_hd__inv_2 _1079_ (
    .A(\reg_0[1] ),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__o22a_2 _1080_ (
    .A1(_0531_),
    .A2(_0513_),
    .B1(_0532_),
    .B2(_0521_),
    .X(_0533_)
  );
  sky130_fd_sc_hd__o22ai_2 _1081_ (
    .A1(_0530_),
    .A2(_0511_),
    .B1(_0518_),
    .B2(_0533_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__buf_1 _1082_ (
    .A(_0523_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__buf_1 _1083_ (
    .A(_0534_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__inv_2 _1084_ (
    .A(\reg_rdata[0] ),
    .Y(_0535_)
  );
  sky130_fd_sc_hd__inv_2 _1085_ (
    .A(\reg_0[0] ),
    .Y(_0536_)
  );
  sky130_fd_sc_hd__inv_2 _1086_ (
    .A(\reg_1[0] ),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__o22a_2 _1087_ (
    .A1(_0536_),
    .A2(_0521_),
    .B1(_0537_),
    .B2(_0337_),
    .X(_0538_)
  );
  sky130_fd_sc_hd__o22ai_2 _1088_ (
    .A1(_0535_),
    .A2(_0355_),
    .B1(_0518_),
    .B2(_0538_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__buf_1 _1089_ (
    .A(_0523_),
    .X(_0539_)
  );
  sky130_fd_sc_hd__buf_1 _1090_ (
    .A(_0539_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__buf_1 _1091_ (
    .A(_0212_),
    .X(_0540_)
  );
  sky130_fd_sc_hd__buf_1 _1092_ (
    .A(_0540_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__buf_1 _1093_ (
    .A(_0196_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__buf_1 _1094_ (
    .A(_0541_),
    .X(_0542_)
  );
  sky130_fd_sc_hd__inv_2 _1095_ (
    .A(reg_ack),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__nor2_2 _1096_ (
    .A(_0542_),
    .B(_0543_),
    .Y(wbm_ack_o)
  );
  sky130_fd_sc_hd__o21a_2 _1097_ (
    .A1(_0542_),
    .A2(_0543_),
    .B1(wbm_stb_i),
    .X(_0001_)
  );
  sky130_fd_sc_hd__buf_1 _1098_ (
    .A(_0542_),
    .X(_0544_)
  );
  sky130_fd_sc_hd__nor2_2 _1099_ (
    .A(_0535_),
    .B(_0544_),
    .Y(wbm_dat_o[0])
  );
  sky130_fd_sc_hd__nor2_2 _1100_ (
    .A(_0530_),
    .B(_0544_),
    .Y(wbm_dat_o[1])
  );
  sky130_fd_sc_hd__nor2_2 _1101_ (
    .A(_0525_),
    .B(_0544_),
    .Y(wbm_dat_o[2])
  );
  sky130_fd_sc_hd__nor2_2 _1102_ (
    .A(_0517_),
    .B(_0544_),
    .Y(wbm_dat_o[3])
  );
  sky130_fd_sc_hd__buf_1 _1103_ (
    .A(_0542_),
    .X(_0545_)
  );
  sky130_fd_sc_hd__nor2_2 _1104_ (
    .A(_0510_),
    .B(_0545_),
    .Y(wbm_dat_o[4])
  );
  sky130_fd_sc_hd__nor2_2 _1105_ (
    .A(_0505_),
    .B(_0545_),
    .Y(wbm_dat_o[5])
  );
  sky130_fd_sc_hd__nor2_2 _1106_ (
    .A(_0500_),
    .B(_0545_),
    .Y(wbm_dat_o[6])
  );
  sky130_fd_sc_hd__nor2_2 _1107_ (
    .A(_0492_),
    .B(_0545_),
    .Y(wbm_dat_o[7])
  );
  sky130_fd_sc_hd__buf_1 _1108_ (
    .A(_0541_),
    .X(_0546_)
  );
  sky130_fd_sc_hd__buf_1 _1109_ (
    .A(_0546_),
    .X(_0547_)
  );
  sky130_fd_sc_hd__nor2_2 _1110_ (
    .A(_0485_),
    .B(_0547_),
    .Y(wbm_dat_o[8])
  );
  sky130_fd_sc_hd__nor2_2 _1111_ (
    .A(_0480_),
    .B(_0547_),
    .Y(wbm_dat_o[9])
  );
  sky130_fd_sc_hd__nor2_2 _1112_ (
    .A(_0475_),
    .B(_0547_),
    .Y(wbm_dat_o[10])
  );
  sky130_fd_sc_hd__nor2_2 _1113_ (
    .A(_0467_),
    .B(_0547_),
    .Y(wbm_dat_o[11])
  );
  sky130_fd_sc_hd__buf_1 _1114_ (
    .A(_0546_),
    .X(_0548_)
  );
  sky130_fd_sc_hd__nor2_2 _1115_ (
    .A(_0460_),
    .B(_0548_),
    .Y(wbm_dat_o[12])
  );
  sky130_fd_sc_hd__nor2_2 _1116_ (
    .A(_0455_),
    .B(_0548_),
    .Y(wbm_dat_o[13])
  );
  sky130_fd_sc_hd__nor2_2 _1117_ (
    .A(_0450_),
    .B(_0548_),
    .Y(wbm_dat_o[14])
  );
  sky130_fd_sc_hd__nor2_2 _1118_ (
    .A(_0440_),
    .B(_0548_),
    .Y(wbm_dat_o[15])
  );
  sky130_fd_sc_hd__buf_1 _1119_ (
    .A(_0546_),
    .X(_0549_)
  );
  sky130_fd_sc_hd__nor2_2 _1120_ (
    .A(_0431_),
    .B(_0549_),
    .Y(wbm_dat_o[16])
  );
  sky130_fd_sc_hd__nor2_2 _1121_ (
    .A(_0426_),
    .B(_0549_),
    .Y(wbm_dat_o[17])
  );
  sky130_fd_sc_hd__nor2_2 _1122_ (
    .A(_0421_),
    .B(_0549_),
    .Y(wbm_dat_o[18])
  );
  sky130_fd_sc_hd__nor2_2 _1123_ (
    .A(_0412_),
    .B(_0549_),
    .Y(wbm_dat_o[19])
  );
  sky130_fd_sc_hd__buf_1 _1124_ (
    .A(_0546_),
    .X(_0550_)
  );
  sky130_fd_sc_hd__nor2_2 _1125_ (
    .A(_0405_),
    .B(_0550_),
    .Y(wbm_dat_o[20])
  );
  sky130_fd_sc_hd__nor2_2 _1126_ (
    .A(_0400_),
    .B(_0550_),
    .Y(wbm_dat_o[21])
  );
  sky130_fd_sc_hd__nor2_2 _1127_ (
    .A(_0395_),
    .B(_0550_),
    .Y(wbm_dat_o[22])
  );
  sky130_fd_sc_hd__nor2_2 _1128_ (
    .A(_0387_),
    .B(_0550_),
    .Y(wbm_dat_o[23])
  );
  sky130_fd_sc_hd__buf_1 _1129_ (
    .A(_0541_),
    .X(_0551_)
  );
  sky130_fd_sc_hd__nor2_2 _1130_ (
    .A(_0380_),
    .B(_0551_),
    .Y(wbm_dat_o[24])
  );
  sky130_fd_sc_hd__nor2_2 _1131_ (
    .A(_0375_),
    .B(_0551_),
    .Y(wbm_dat_o[25])
  );
  sky130_fd_sc_hd__nor2_2 _1132_ (
    .A(_0370_),
    .B(_0551_),
    .Y(wbm_dat_o[26])
  );
  sky130_fd_sc_hd__nor2_2 _1133_ (
    .A(_0362_),
    .B(_0551_),
    .Y(wbm_dat_o[27])
  );
  sky130_fd_sc_hd__buf_1 _1134_ (
    .A(_0541_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__nor2_2 _1135_ (
    .A(_0354_),
    .B(_0552_),
    .Y(wbm_dat_o[28])
  );
  sky130_fd_sc_hd__nor2_2 _1136_ (
    .A(_0349_),
    .B(_0552_),
    .Y(wbm_dat_o[29])
  );
  sky130_fd_sc_hd__nor2_2 _1137_ (
    .A(_0344_),
    .B(_0552_),
    .Y(wbm_dat_o[30])
  );
  sky130_fd_sc_hd__nor2_2 _1138_ (
    .A(_0332_),
    .B(_0552_),
    .Y(wbm_dat_o[31])
  );
  sky130_fd_sc_hd__buf_1 _1139_ (
    .A(_0212_),
    .X(_0553_)
  );
  sky130_fd_sc_hd__buf_1 _1140_ (
    .A(_0553_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__conb_1 _1141_ (
    .LO(wbm_err_o)
  );
  sky130_fd_sc_hd__dfrtp_2 _1142_ (
    .CLK(wbm_clk_i),
    .D(_0000_),
    .Q(reg_ack),
    .RESET_B(_0011_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1143_ (
    .CLK(wbm_clk_i),
    .D(_0001_),
    .Q(wb_req),
    .RESET_B(_0012_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1144_ (
    .CLK(wbm_clk_i),
    .D(_0109_),
    .Q(\reg_rdata[0] ),
    .RESET_B(_0013_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1145_ (
    .CLK(wbm_clk_i),
    .D(_0110_),
    .Q(\reg_rdata[1] ),
    .RESET_B(_0014_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1146_ (
    .CLK(wbm_clk_i),
    .D(_0111_),
    .Q(\reg_rdata[2] ),
    .RESET_B(_0015_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1147_ (
    .CLK(wbm_clk_i),
    .D(_0112_),
    .Q(\reg_rdata[3] ),
    .RESET_B(_0016_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1148_ (
    .CLK(wbm_clk_i),
    .D(_0113_),
    .Q(\reg_rdata[4] ),
    .RESET_B(_0017_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1149_ (
    .CLK(wbm_clk_i),
    .D(_0114_),
    .Q(\reg_rdata[5] ),
    .RESET_B(_0018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1150_ (
    .CLK(wbm_clk_i),
    .D(_0115_),
    .Q(\reg_rdata[6] ),
    .RESET_B(_0019_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1151_ (
    .CLK(wbm_clk_i),
    .D(_0116_),
    .Q(\reg_rdata[7] ),
    .RESET_B(_0020_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1152_ (
    .CLK(wbm_clk_i),
    .D(_0117_),
    .Q(\reg_rdata[8] ),
    .RESET_B(_0021_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1153_ (
    .CLK(wbm_clk_i),
    .D(_0118_),
    .Q(\reg_rdata[9] ),
    .RESET_B(_0022_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1154_ (
    .CLK(wbm_clk_i),
    .D(_0119_),
    .Q(\reg_rdata[10] ),
    .RESET_B(_0023_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1155_ (
    .CLK(wbm_clk_i),
    .D(_0120_),
    .Q(\reg_rdata[11] ),
    .RESET_B(_0024_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1156_ (
    .CLK(wbm_clk_i),
    .D(_0121_),
    .Q(\reg_rdata[12] ),
    .RESET_B(_0025_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1157_ (
    .CLK(wbm_clk_i),
    .D(_0122_),
    .Q(\reg_rdata[13] ),
    .RESET_B(_0026_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1158_ (
    .CLK(wbm_clk_i),
    .D(_0123_),
    .Q(\reg_rdata[14] ),
    .RESET_B(_0027_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1159_ (
    .CLK(wbm_clk_i),
    .D(_0124_),
    .Q(\reg_rdata[15] ),
    .RESET_B(_0028_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1160_ (
    .CLK(wbm_clk_i),
    .D(_0125_),
    .Q(\reg_rdata[16] ),
    .RESET_B(_0029_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1161_ (
    .CLK(wbm_clk_i),
    .D(_0126_),
    .Q(\reg_rdata[17] ),
    .RESET_B(_0030_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1162_ (
    .CLK(wbm_clk_i),
    .D(_0127_),
    .Q(\reg_rdata[18] ),
    .RESET_B(_0031_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1163_ (
    .CLK(wbm_clk_i),
    .D(_0128_),
    .Q(\reg_rdata[19] ),
    .RESET_B(_0032_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1164_ (
    .CLK(wbm_clk_i),
    .D(_0129_),
    .Q(\reg_rdata[20] ),
    .RESET_B(_0033_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1165_ (
    .CLK(wbm_clk_i),
    .D(_0130_),
    .Q(\reg_rdata[21] ),
    .RESET_B(_0034_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1166_ (
    .CLK(wbm_clk_i),
    .D(_0131_),
    .Q(\reg_rdata[22] ),
    .RESET_B(_0035_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1167_ (
    .CLK(wbm_clk_i),
    .D(_0132_),
    .Q(\reg_rdata[23] ),
    .RESET_B(_0036_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1168_ (
    .CLK(wbm_clk_i),
    .D(_0133_),
    .Q(\reg_rdata[24] ),
    .RESET_B(_0037_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1169_ (
    .CLK(wbm_clk_i),
    .D(_0134_),
    .Q(\reg_rdata[25] ),
    .RESET_B(_0038_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1170_ (
    .CLK(wbm_clk_i),
    .D(_0135_),
    .Q(\reg_rdata[26] ),
    .RESET_B(_0039_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1171_ (
    .CLK(wbm_clk_i),
    .D(_0136_),
    .Q(\reg_rdata[27] ),
    .RESET_B(_0040_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1172_ (
    .CLK(wbm_clk_i),
    .D(_0137_),
    .Q(\reg_rdata[28] ),
    .RESET_B(_0041_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1173_ (
    .CLK(wbm_clk_i),
    .D(_0138_),
    .Q(\reg_rdata[29] ),
    .RESET_B(_0042_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1174_ (
    .CLK(wbm_clk_i),
    .D(_0139_),
    .Q(\reg_rdata[30] ),
    .RESET_B(_0043_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1175_ (
    .CLK(wbm_clk_i),
    .D(_0140_),
    .Q(\reg_rdata[31] ),
    .RESET_B(_0044_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1176_ (
    .CLK(wbm_clk_i),
    .D(_0141_),
    .Q(\reg_0[0] ),
    .RESET_B(_0045_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1177_ (
    .CLK(wbm_clk_i),
    .D(_0142_),
    .Q(\reg_0[1] ),
    .RESET_B(_0046_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1178_ (
    .CLK(wbm_clk_i),
    .D(_0143_),
    .Q(\reg_0[2] ),
    .RESET_B(_0047_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1179_ (
    .CLK(wbm_clk_i),
    .D(_0144_),
    .Q(\reg_0[3] ),
    .RESET_B(_0048_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1180_ (
    .CLK(wbm_clk_i),
    .D(_0145_),
    .Q(\reg_0[4] ),
    .RESET_B(_0049_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1181_ (
    .CLK(wbm_clk_i),
    .D(_0146_),
    .Q(\reg_0[5] ),
    .RESET_B(_0050_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1182_ (
    .CLK(wbm_clk_i),
    .D(_0147_),
    .Q(\reg_0[6] ),
    .RESET_B(_0051_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1183_ (
    .CLK(wbm_clk_i),
    .D(_0148_),
    .Q(\reg_0[7] ),
    .RESET_B(_0052_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1184_ (
    .CLK(wbm_clk_i),
    .D(_0149_),
    .Q(\reg_0[8] ),
    .RESET_B(_0053_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1185_ (
    .CLK(wbm_clk_i),
    .D(_0150_),
    .Q(\reg_0[9] ),
    .RESET_B(_0054_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1186_ (
    .CLK(wbm_clk_i),
    .D(_0151_),
    .Q(\reg_0[10] ),
    .RESET_B(_0055_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1187_ (
    .CLK(wbm_clk_i),
    .D(_0152_),
    .Q(\reg_0[11] ),
    .RESET_B(_0056_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1188_ (
    .CLK(wbm_clk_i),
    .D(_0153_),
    .Q(\reg_0[12] ),
    .RESET_B(_0057_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1189_ (
    .CLK(wbm_clk_i),
    .D(_0154_),
    .Q(\reg_0[13] ),
    .RESET_B(_0058_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1190_ (
    .CLK(wbm_clk_i),
    .D(_0155_),
    .Q(\reg_0[14] ),
    .RESET_B(_0059_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1191_ (
    .CLK(wbm_clk_i),
    .D(_0156_),
    .Q(\reg_0[15] ),
    .RESET_B(_0060_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1192_ (
    .CLK(wbm_clk_i),
    .D(_0157_),
    .Q(\reg_0[16] ),
    .RESET_B(_0061_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1193_ (
    .CLK(wbm_clk_i),
    .D(_0158_),
    .Q(\reg_0[17] ),
    .RESET_B(_0062_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1194_ (
    .CLK(wbm_clk_i),
    .D(_0159_),
    .Q(\reg_0[18] ),
    .RESET_B(_0063_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1195_ (
    .CLK(wbm_clk_i),
    .D(_0160_),
    .Q(\reg_0[19] ),
    .RESET_B(_0064_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1196_ (
    .CLK(wbm_clk_i),
    .D(_0161_),
    .Q(\reg_0[20] ),
    .RESET_B(_0065_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1197_ (
    .CLK(wbm_clk_i),
    .D(_0162_),
    .Q(\reg_0[21] ),
    .RESET_B(_0066_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1198_ (
    .CLK(wbm_clk_i),
    .D(_0163_),
    .Q(\reg_0[22] ),
    .RESET_B(_0067_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1199_ (
    .CLK(wbm_clk_i),
    .D(_0164_),
    .Q(\reg_0[23] ),
    .RESET_B(_0068_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1200_ (
    .CLK(wbm_clk_i),
    .D(_0165_),
    .Q(\reg_0[24] ),
    .RESET_B(_0069_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1201_ (
    .CLK(wbm_clk_i),
    .D(_0166_),
    .Q(\reg_0[25] ),
    .RESET_B(_0070_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1202_ (
    .CLK(wbm_clk_i),
    .D(_0167_),
    .Q(\reg_0[26] ),
    .RESET_B(_0071_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1203_ (
    .CLK(wbm_clk_i),
    .D(_0168_),
    .Q(\reg_0[27] ),
    .RESET_B(_0072_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1204_ (
    .CLK(wbm_clk_i),
    .D(_0169_),
    .Q(\reg_0[28] ),
    .RESET_B(_0073_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1205_ (
    .CLK(wbm_clk_i),
    .D(_0170_),
    .Q(\reg_0[29] ),
    .RESET_B(_0074_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1206_ (
    .CLK(wbm_clk_i),
    .D(_0171_),
    .Q(\reg_0[30] ),
    .RESET_B(_0075_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1207_ (
    .CLK(wbm_clk_i),
    .D(_0172_),
    .Q(\reg_0[31] ),
    .RESET_B(_0076_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1208_ (
    .CLK(wbm_clk_i),
    .D(_0173_),
    .Q(\reg_1[0] ),
    .RESET_B(_0077_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1209_ (
    .CLK(wbm_clk_i),
    .D(_0174_),
    .Q(\reg_1[1] ),
    .RESET_B(_0078_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1210_ (
    .CLK(wbm_clk_i),
    .D(_0175_),
    .Q(\reg_1[2] ),
    .RESET_B(_0079_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1211_ (
    .CLK(wbm_clk_i),
    .D(_0176_),
    .Q(\reg_1[3] ),
    .RESET_B(_0080_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1212_ (
    .CLK(wbm_clk_i),
    .D(_0177_),
    .Q(\reg_1[4] ),
    .RESET_B(_0081_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1213_ (
    .CLK(wbm_clk_i),
    .D(_0178_),
    .Q(\reg_1[5] ),
    .RESET_B(_0082_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1214_ (
    .CLK(wbm_clk_i),
    .D(_0179_),
    .Q(\reg_1[6] ),
    .RESET_B(_0083_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1215_ (
    .CLK(wbm_clk_i),
    .D(_0180_),
    .Q(\reg_1[7] ),
    .RESET_B(_0084_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1216_ (
    .CLK(wbm_clk_i),
    .D(_0181_),
    .Q(\reg_1[8] ),
    .RESET_B(_0085_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1217_ (
    .CLK(wbm_clk_i),
    .D(_0182_),
    .Q(\reg_1[9] ),
    .RESET_B(_0086_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1218_ (
    .CLK(wbm_clk_i),
    .D(_0183_),
    .Q(\reg_1[10] ),
    .RESET_B(_0087_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1219_ (
    .CLK(wbm_clk_i),
    .D(_0184_),
    .Q(\reg_1[11] ),
    .RESET_B(_0088_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1220_ (
    .CLK(wbm_clk_i),
    .D(_0185_),
    .Q(\reg_1[12] ),
    .RESET_B(_0089_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1221_ (
    .CLK(wbm_clk_i),
    .D(_0186_),
    .Q(\reg_1[13] ),
    .RESET_B(_0090_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1222_ (
    .CLK(wbm_clk_i),
    .D(_0187_),
    .Q(\reg_1[14] ),
    .RESET_B(_0091_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1223_ (
    .CLK(wbm_clk_i),
    .D(_0188_),
    .Q(\reg_1[15] ),
    .RESET_B(_0092_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1224_ (
    .CLK(wbm_clk_i),
    .D(_0189_),
    .Q(\reg_1[16] ),
    .RESET_B(_0093_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1225_ (
    .CLK(wbm_clk_i),
    .D(_0190_),
    .Q(\reg_1[17] ),
    .RESET_B(_0094_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1226_ (
    .CLK(wbm_clk_i),
    .D(_0191_),
    .Q(\reg_1[18] ),
    .RESET_B(_0095_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1227_ (
    .CLK(wbm_clk_i),
    .D(_0192_),
    .Q(\reg_1[19] ),
    .RESET_B(_0096_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1228_ (
    .CLK(wbm_clk_i),
    .D(_0193_),
    .Q(\reg_1[20] ),
    .RESET_B(_0097_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1229_ (
    .CLK(wbm_clk_i),
    .D(_0194_),
    .Q(\reg_1[21] ),
    .RESET_B(_0098_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1230_ (
    .CLK(wbm_clk_i),
    .D(_0195_),
    .Q(\reg_1[22] ),
    .RESET_B(_0099_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1231_ (
    .CLK(wbm_clk_i),
    .D(_0100_),
    .Q(\reg_1[23] ),
    .RESET_B(_0002_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1232_ (
    .CLK(wbm_clk_i),
    .D(_0101_),
    .Q(\reg_1[24] ),
    .RESET_B(_0003_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1233_ (
    .CLK(wbm_clk_i),
    .D(_0102_),
    .Q(\reg_1[25] ),
    .RESET_B(_0004_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1234_ (
    .CLK(wbm_clk_i),
    .D(_0103_),
    .Q(\reg_1[26] ),
    .RESET_B(_0005_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1235_ (
    .CLK(wbm_clk_i),
    .D(_0104_),
    .Q(\reg_1[27] ),
    .RESET_B(_0006_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1236_ (
    .CLK(wbm_clk_i),
    .D(_0105_),
    .Q(\reg_1[28] ),
    .RESET_B(_0007_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1237_ (
    .CLK(wbm_clk_i),
    .D(_0106_),
    .Q(\reg_1[29] ),
    .RESET_B(_0008_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1238_ (
    .CLK(wbm_clk_i),
    .D(_0107_),
    .Q(\reg_1[30] ),
    .RESET_B(_0009_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1239_ (
    .CLK(wbm_clk_i),
    .D(_0108_),
    .Q(\reg_1[31] ),
    .RESET_B(_0010_)
  );
endmodule
