/* Generated by Yosys 0.9+4052 (git sha1 d061b0e, gcc 8.3.1 -fPIC -Os) */

module wb_host(wbm_rst_i, wbm_clk_i, wbm_cyc_i, wbm_stb_i, wbm_adr_i, wbm_we_i, wbm_dat_i, wbm_sel_i, wbm_dat_o, wbm_ack_o, wbm_err_o);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire \reg_0[0] ;
  wire \reg_0[10] ;
  wire \reg_0[11] ;
  wire \reg_0[12] ;
  wire \reg_0[13] ;
  wire \reg_0[14] ;
  wire \reg_0[15] ;
  wire \reg_0[16] ;
  wire \reg_0[17] ;
  wire \reg_0[18] ;
  wire \reg_0[19] ;
  wire \reg_0[1] ;
  wire \reg_0[20] ;
  wire \reg_0[21] ;
  wire \reg_0[22] ;
  wire \reg_0[23] ;
  wire \reg_0[24] ;
  wire \reg_0[25] ;
  wire \reg_0[26] ;
  wire \reg_0[27] ;
  wire \reg_0[28] ;
  wire \reg_0[29] ;
  wire \reg_0[2] ;
  wire \reg_0[30] ;
  wire \reg_0[31] ;
  wire \reg_0[3] ;
  wire \reg_0[4] ;
  wire \reg_0[5] ;
  wire \reg_0[6] ;
  wire \reg_0[7] ;
  wire \reg_0[8] ;
  wire \reg_0[9] ;
  wire \reg_1[0] ;
  wire \reg_1[10] ;
  wire \reg_1[11] ;
  wire \reg_1[12] ;
  wire \reg_1[13] ;
  wire \reg_1[14] ;
  wire \reg_1[15] ;
  wire \reg_1[16] ;
  wire \reg_1[17] ;
  wire \reg_1[18] ;
  wire \reg_1[19] ;
  wire \reg_1[1] ;
  wire \reg_1[20] ;
  wire \reg_1[21] ;
  wire \reg_1[22] ;
  wire \reg_1[23] ;
  wire \reg_1[24] ;
  wire \reg_1[25] ;
  wire \reg_1[26] ;
  wire \reg_1[27] ;
  wire \reg_1[28] ;
  wire \reg_1[29] ;
  wire \reg_1[2] ;
  wire \reg_1[30] ;
  wire \reg_1[31] ;
  wire \reg_1[3] ;
  wire \reg_1[4] ;
  wire \reg_1[5] ;
  wire \reg_1[6] ;
  wire \reg_1[7] ;
  wire \reg_1[8] ;
  wire \reg_1[9] ;
  wire reg_ack;
  wire \reg_rdata[0] ;
  wire \reg_rdata[10] ;
  wire \reg_rdata[11] ;
  wire \reg_rdata[12] ;
  wire \reg_rdata[13] ;
  wire \reg_rdata[14] ;
  wire \reg_rdata[15] ;
  wire \reg_rdata[16] ;
  wire \reg_rdata[17] ;
  wire \reg_rdata[18] ;
  wire \reg_rdata[19] ;
  wire \reg_rdata[1] ;
  wire \reg_rdata[20] ;
  wire \reg_rdata[21] ;
  wire \reg_rdata[22] ;
  wire \reg_rdata[23] ;
  wire \reg_rdata[24] ;
  wire \reg_rdata[25] ;
  wire \reg_rdata[26] ;
  wire \reg_rdata[27] ;
  wire \reg_rdata[28] ;
  wire \reg_rdata[29] ;
  wire \reg_rdata[2] ;
  wire \reg_rdata[30] ;
  wire \reg_rdata[31] ;
  wire \reg_rdata[3] ;
  wire \reg_rdata[4] ;
  wire \reg_rdata[5] ;
  wire \reg_rdata[6] ;
  wire \reg_rdata[7] ;
  wire \reg_rdata[8] ;
  wire \reg_rdata[9] ;
  wire wb_req;
  output wbm_ack_o;
  input [31:0] wbm_adr_i;
  input wbm_clk_i;
  input wbm_cyc_i;
  input [31:0] wbm_dat_i;
  output [31:0] wbm_dat_o;
  output wbm_err_o;
  input wbm_rst_i;
  input [3:0] wbm_sel_i;
  input wbm_stb_i;
  input wbm_we_i;
  sky130_fd_sc_hd__inv_2 _0457_ (
    .A(wb_req),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__inv_2 _0458_ (
    .A(wbm_we_i),
    .Y(_0197_)
  );
  sky130_fd_sc_hd__or3b_2 _0459_ (
    .A(wbm_adr_i[3]),
    .B(wbm_adr_i[4]),
    .C_N(wbm_adr_i[2]),
    .X(_0198_)
  );
  sky130_fd_sc_hd__or3_2 _0460_ (
    .A(_0196_),
    .B(_0197_),
    .C(_0198_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__buf_1 _0461_ (
    .A(_0199_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__buf_1 _0462_ (
    .A(_0200_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__inv_2 _0463_ (
    .A(_0199_),
    .Y(_0202_)
  );
  sky130_fd_sc_hd__buf_1 _0464_ (
    .A(_0202_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__buf_1 _0465_ (
    .A(_0203_),
    .X(_0204_)
  );
  sky130_fd_sc_hd__a22o_2 _0466_ (
    .A1(\reg_1[31] ),
    .A2(_0201_),
    .B1(wbm_dat_i[31]),
    .B2(_0204_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__inv_2 _0467_ (
    .A(wbm_rst_i),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__buf_1 _0468_ (
    .A(_0205_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__buf_1 _0469_ (
    .A(_0206_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__buf_1 _0470_ (
    .A(_0207_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__a22o_2 _0471_ (
    .A1(\reg_1[30] ),
    .A2(_0201_),
    .B1(wbm_dat_i[30]),
    .B2(_0204_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__buf_1 _0472_ (
    .A(_0009_),
    .X(_0008_)
  );
  sky130_fd_sc_hd__a22o_2 _0473_ (
    .A1(\reg_1[29] ),
    .A2(_0201_),
    .B1(wbm_dat_i[29]),
    .B2(_0204_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__buf_1 _0474_ (
    .A(_0009_),
    .X(_0007_)
  );
  sky130_fd_sc_hd__a22o_2 _0475_ (
    .A1(\reg_1[28] ),
    .A2(_0201_),
    .B1(wbm_dat_i[28]),
    .B2(_0204_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__buf_1 _0476_ (
    .A(_0009_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__buf_1 _0477_ (
    .A(_0200_),
    .X(_0208_)
  );
  sky130_fd_sc_hd__buf_1 _0478_ (
    .A(_0203_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__a22o_2 _0479_ (
    .A1(\reg_1[27] ),
    .A2(_0208_),
    .B1(wbm_dat_i[27]),
    .B2(_0209_),
    .X(_0104_)
  );
  sky130_fd_sc_hd__buf_1 _0480_ (
    .A(_0207_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__buf_1 _0481_ (
    .A(_0210_),
    .X(_0005_)
  );
  sky130_fd_sc_hd__a22o_2 _0482_ (
    .A1(\reg_1[26] ),
    .A2(_0208_),
    .B1(wbm_dat_i[26]),
    .B2(_0209_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__buf_1 _0483_ (
    .A(_0210_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__a22o_2 _0484_ (
    .A1(\reg_1[25] ),
    .A2(_0208_),
    .B1(wbm_dat_i[25]),
    .B2(_0209_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__buf_1 _0485_ (
    .A(_0210_),
    .X(_0003_)
  );
  sky130_fd_sc_hd__a22o_2 _0486_ (
    .A1(\reg_1[24] ),
    .A2(_0208_),
    .B1(wbm_dat_i[24]),
    .B2(_0209_),
    .X(_0101_)
  );
  sky130_fd_sc_hd__buf_1 _0487_ (
    .A(_0210_),
    .X(_0002_)
  );
  sky130_fd_sc_hd__buf_1 _0488_ (
    .A(_0200_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__buf_1 _0489_ (
    .A(_0203_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__a22o_2 _0490_ (
    .A1(\reg_1[23] ),
    .A2(_0211_),
    .B1(wbm_dat_i[23]),
    .B2(_0212_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__buf_1 _0491_ (
    .A(_0205_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__buf_1 _0492_ (
    .A(_0213_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__buf_1 _0493_ (
    .A(_0214_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__buf_1 _0494_ (
    .A(_0215_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__a22o_2 _0495_ (
    .A1(\reg_1[22] ),
    .A2(_0211_),
    .B1(wbm_dat_i[22]),
    .B2(_0212_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__buf_1 _0496_ (
    .A(_0215_),
    .X(_0098_)
  );
  sky130_fd_sc_hd__a22o_2 _0497_ (
    .A1(\reg_1[21] ),
    .A2(_0211_),
    .B1(wbm_dat_i[21]),
    .B2(_0212_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__buf_1 _0498_ (
    .A(_0215_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__a22o_2 _0499_ (
    .A1(\reg_1[20] ),
    .A2(_0211_),
    .B1(wbm_dat_i[20]),
    .B2(_0212_),
    .X(_0193_)
  );
  sky130_fd_sc_hd__buf_1 _0500_ (
    .A(_0215_),
    .X(_0096_)
  );
  sky130_fd_sc_hd__buf_1 _0501_ (
    .A(_0200_),
    .X(_0216_)
  );
  sky130_fd_sc_hd__buf_1 _0502_ (
    .A(_0203_),
    .X(_0217_)
  );
  sky130_fd_sc_hd__a22o_2 _0503_ (
    .A1(\reg_1[19] ),
    .A2(_0216_),
    .B1(wbm_dat_i[19]),
    .B2(_0217_),
    .X(_0192_)
  );
  sky130_fd_sc_hd__buf_1 _0504_ (
    .A(_0214_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__buf_1 _0505_ (
    .A(_0218_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__a22o_2 _0506_ (
    .A1(\reg_1[18] ),
    .A2(_0216_),
    .B1(wbm_dat_i[18]),
    .B2(_0217_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__buf_1 _0507_ (
    .A(_0218_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__a22o_2 _0508_ (
    .A1(\reg_1[17] ),
    .A2(_0216_),
    .B1(wbm_dat_i[17]),
    .B2(_0217_),
    .X(_0190_)
  );
  sky130_fd_sc_hd__buf_1 _0509_ (
    .A(_0218_),
    .X(_0093_)
  );
  sky130_fd_sc_hd__a22o_2 _0510_ (
    .A1(\reg_1[16] ),
    .A2(_0216_),
    .B1(wbm_dat_i[16]),
    .B2(_0217_),
    .X(_0189_)
  );
  sky130_fd_sc_hd__buf_1 _0511_ (
    .A(_0218_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__buf_1 _0512_ (
    .A(_0199_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__buf_1 _0513_ (
    .A(_0219_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__buf_1 _0514_ (
    .A(_0202_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__buf_1 _0515_ (
    .A(_0221_),
    .X(_0222_)
  );
  sky130_fd_sc_hd__a22o_2 _0516_ (
    .A1(\reg_1[15] ),
    .A2(_0220_),
    .B1(wbm_dat_i[15]),
    .B2(_0222_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__buf_1 _0517_ (
    .A(_0214_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__buf_1 _0518_ (
    .A(_0223_),
    .X(_0091_)
  );
  sky130_fd_sc_hd__a22o_2 _0519_ (
    .A1(\reg_1[14] ),
    .A2(_0220_),
    .B1(wbm_dat_i[14]),
    .B2(_0222_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__buf_1 _0520_ (
    .A(_0223_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__a22o_2 _0521_ (
    .A1(\reg_1[13] ),
    .A2(_0220_),
    .B1(wbm_dat_i[13]),
    .B2(_0222_),
    .X(_0186_)
  );
  sky130_fd_sc_hd__buf_1 _0522_ (
    .A(_0223_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__a22o_2 _0523_ (
    .A1(\reg_1[12] ),
    .A2(_0220_),
    .B1(wbm_dat_i[12]),
    .B2(_0222_),
    .X(_0185_)
  );
  sky130_fd_sc_hd__buf_1 _0524_ (
    .A(_0223_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__buf_1 _0525_ (
    .A(_0219_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__buf_1 _0526_ (
    .A(_0221_),
    .X(_0225_)
  );
  sky130_fd_sc_hd__a22o_2 _0527_ (
    .A1(\reg_1[11] ),
    .A2(_0224_),
    .B1(wbm_dat_i[11]),
    .B2(_0225_),
    .X(_0184_)
  );
  sky130_fd_sc_hd__buf_1 _0528_ (
    .A(_0214_),
    .X(_0226_)
  );
  sky130_fd_sc_hd__buf_1 _0529_ (
    .A(_0226_),
    .X(_0087_)
  );
  sky130_fd_sc_hd__a22o_2 _0530_ (
    .A1(\reg_1[10] ),
    .A2(_0224_),
    .B1(wbm_dat_i[10]),
    .B2(_0225_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__buf_1 _0531_ (
    .A(_0226_),
    .X(_0086_)
  );
  sky130_fd_sc_hd__a22o_2 _0532_ (
    .A1(\reg_1[9] ),
    .A2(_0224_),
    .B1(wbm_dat_i[9]),
    .B2(_0225_),
    .X(_0182_)
  );
  sky130_fd_sc_hd__buf_1 _0533_ (
    .A(_0226_),
    .X(_0085_)
  );
  sky130_fd_sc_hd__a22o_2 _0534_ (
    .A1(\reg_1[8] ),
    .A2(_0224_),
    .B1(wbm_dat_i[8]),
    .B2(_0225_),
    .X(_0181_)
  );
  sky130_fd_sc_hd__buf_1 _0535_ (
    .A(_0226_),
    .X(_0084_)
  );
  sky130_fd_sc_hd__buf_1 _0536_ (
    .A(_0219_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__buf_1 _0537_ (
    .A(_0221_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__a22o_2 _0538_ (
    .A1(\reg_1[7] ),
    .A2(_0227_),
    .B1(wbm_dat_i[7]),
    .B2(_0228_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__buf_1 _0539_ (
    .A(_0213_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__buf_1 _0540_ (
    .A(_0229_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__buf_1 _0541_ (
    .A(_0230_),
    .X(_0083_)
  );
  sky130_fd_sc_hd__a22o_2 _0542_ (
    .A1(\reg_1[6] ),
    .A2(_0227_),
    .B1(wbm_dat_i[6]),
    .B2(_0228_),
    .X(_0179_)
  );
  sky130_fd_sc_hd__buf_1 _0543_ (
    .A(_0230_),
    .X(_0082_)
  );
  sky130_fd_sc_hd__a22o_2 _0544_ (
    .A1(\reg_1[5] ),
    .A2(_0227_),
    .B1(wbm_dat_i[5]),
    .B2(_0228_),
    .X(_0178_)
  );
  sky130_fd_sc_hd__buf_1 _0545_ (
    .A(_0230_),
    .X(_0081_)
  );
  sky130_fd_sc_hd__a22o_2 _0546_ (
    .A1(\reg_1[4] ),
    .A2(_0227_),
    .B1(wbm_dat_i[4]),
    .B2(_0228_),
    .X(_0177_)
  );
  sky130_fd_sc_hd__buf_1 _0547_ (
    .A(_0230_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__buf_1 _0548_ (
    .A(_0219_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__buf_1 _0549_ (
    .A(_0221_),
    .X(_0232_)
  );
  sky130_fd_sc_hd__a22o_2 _0550_ (
    .A1(\reg_1[3] ),
    .A2(_0231_),
    .B1(wbm_dat_i[3]),
    .B2(_0232_),
    .X(_0176_)
  );
  sky130_fd_sc_hd__buf_1 _0551_ (
    .A(_0229_),
    .X(_0233_)
  );
  sky130_fd_sc_hd__buf_1 _0552_ (
    .A(_0233_),
    .X(_0079_)
  );
  sky130_fd_sc_hd__a22o_2 _0553_ (
    .A1(\reg_1[2] ),
    .A2(_0231_),
    .B1(wbm_dat_i[2]),
    .B2(_0232_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__buf_1 _0554_ (
    .A(_0233_),
    .X(_0078_)
  );
  sky130_fd_sc_hd__a22o_2 _0555_ (
    .A1(\reg_1[1] ),
    .A2(_0231_),
    .B1(wbm_dat_i[1]),
    .B2(_0232_),
    .X(_0174_)
  );
  sky130_fd_sc_hd__buf_1 _0556_ (
    .A(_0233_),
    .X(_0077_)
  );
  sky130_fd_sc_hd__a22o_2 _0557_ (
    .A1(\reg_1[0] ),
    .A2(_0231_),
    .B1(wbm_dat_i[0]),
    .B2(_0232_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__buf_1 _0558_ (
    .A(_0233_),
    .X(_0076_)
  );
  sky130_fd_sc_hd__or3_2 _0559_ (
    .A(wbm_adr_i[3]),
    .B(wbm_adr_i[2]),
    .C(wbm_adr_i[4]),
    .X(_0234_)
  );
  sky130_fd_sc_hd__or3_2 _0560_ (
    .A(_0196_),
    .B(_0197_),
    .C(_0234_),
    .X(_0235_)
  );
  sky130_fd_sc_hd__buf_1 _0561_ (
    .A(_0235_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__buf_1 _0562_ (
    .A(_0236_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__inv_2 _0563_ (
    .A(_0235_),
    .Y(_0238_)
  );
  sky130_fd_sc_hd__buf_1 _0564_ (
    .A(_0238_),
    .X(_0239_)
  );
  sky130_fd_sc_hd__buf_1 _0565_ (
    .A(_0239_),
    .X(_0240_)
  );
  sky130_fd_sc_hd__a22o_2 _0566_ (
    .A1(\reg_0[31] ),
    .A2(_0237_),
    .B1(wbm_dat_i[31]),
    .B2(_0240_),
    .X(_0172_)
  );
  sky130_fd_sc_hd__buf_1 _0567_ (
    .A(_0229_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__buf_1 _0568_ (
    .A(_0241_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__a22o_2 _0569_ (
    .A1(\reg_0[30] ),
    .A2(_0237_),
    .B1(wbm_dat_i[30]),
    .B2(_0240_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__buf_1 _0570_ (
    .A(_0241_),
    .X(_0074_)
  );
  sky130_fd_sc_hd__a22o_2 _0571_ (
    .A1(\reg_0[29] ),
    .A2(_0237_),
    .B1(wbm_dat_i[29]),
    .B2(_0240_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__buf_1 _0572_ (
    .A(_0241_),
    .X(_0073_)
  );
  sky130_fd_sc_hd__a22o_2 _0573_ (
    .A1(\reg_0[28] ),
    .A2(_0237_),
    .B1(wbm_dat_i[28]),
    .B2(_0240_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__buf_1 _0574_ (
    .A(_0241_),
    .X(_0072_)
  );
  sky130_fd_sc_hd__buf_1 _0575_ (
    .A(_0236_),
    .X(_0242_)
  );
  sky130_fd_sc_hd__buf_1 _0576_ (
    .A(_0239_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__a22o_2 _0577_ (
    .A1(\reg_0[27] ),
    .A2(_0242_),
    .B1(wbm_dat_i[27]),
    .B2(_0243_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__buf_1 _0578_ (
    .A(_0229_),
    .X(_0244_)
  );
  sky130_fd_sc_hd__buf_1 _0579_ (
    .A(_0244_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__a22o_2 _0580_ (
    .A1(\reg_0[26] ),
    .A2(_0242_),
    .B1(wbm_dat_i[26]),
    .B2(_0243_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__buf_1 _0581_ (
    .A(_0244_),
    .X(_0070_)
  );
  sky130_fd_sc_hd__a22o_2 _0582_ (
    .A1(\reg_0[25] ),
    .A2(_0242_),
    .B1(wbm_dat_i[25]),
    .B2(_0243_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__buf_1 _0583_ (
    .A(_0244_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__a22o_2 _0584_ (
    .A1(\reg_0[24] ),
    .A2(_0242_),
    .B1(wbm_dat_i[24]),
    .B2(_0243_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__buf_1 _0585_ (
    .A(_0244_),
    .X(_0068_)
  );
  sky130_fd_sc_hd__buf_1 _0586_ (
    .A(_0236_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__buf_1 _0587_ (
    .A(_0239_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__a22o_2 _0588_ (
    .A1(\reg_0[23] ),
    .A2(_0245_),
    .B1(wbm_dat_i[23]),
    .B2(_0246_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__buf_1 _0589_ (
    .A(_0206_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__buf_1 _0590_ (
    .A(_0247_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__buf_1 _0591_ (
    .A(_0248_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__a22o_2 _0592_ (
    .A1(\reg_0[22] ),
    .A2(_0245_),
    .B1(wbm_dat_i[22]),
    .B2(_0246_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__buf_1 _0593_ (
    .A(_0248_),
    .X(_0066_)
  );
  sky130_fd_sc_hd__a22o_2 _0594_ (
    .A1(\reg_0[21] ),
    .A2(_0245_),
    .B1(wbm_dat_i[21]),
    .B2(_0246_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__buf_1 _0595_ (
    .A(_0248_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__a22o_2 _0596_ (
    .A1(\reg_0[20] ),
    .A2(_0245_),
    .B1(wbm_dat_i[20]),
    .B2(_0246_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__buf_1 _0597_ (
    .A(_0248_),
    .X(_0064_)
  );
  sky130_fd_sc_hd__buf_1 _0598_ (
    .A(_0236_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__buf_1 _0599_ (
    .A(_0239_),
    .X(_0250_)
  );
  sky130_fd_sc_hd__a22o_2 _0600_ (
    .A1(\reg_0[19] ),
    .A2(_0249_),
    .B1(wbm_dat_i[19]),
    .B2(_0250_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__buf_1 _0601_ (
    .A(_0247_),
    .X(_0251_)
  );
  sky130_fd_sc_hd__buf_1 _0602_ (
    .A(_0251_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__a22o_2 _0603_ (
    .A1(\reg_0[18] ),
    .A2(_0249_),
    .B1(wbm_dat_i[18]),
    .B2(_0250_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__buf_1 _0604_ (
    .A(_0251_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__a22o_2 _0605_ (
    .A1(\reg_0[17] ),
    .A2(_0249_),
    .B1(wbm_dat_i[17]),
    .B2(_0250_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__buf_1 _0606_ (
    .A(_0251_),
    .X(_0061_)
  );
  sky130_fd_sc_hd__a22o_2 _0607_ (
    .A1(\reg_0[16] ),
    .A2(_0249_),
    .B1(wbm_dat_i[16]),
    .B2(_0250_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__buf_1 _0608_ (
    .A(_0251_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__buf_1 _0609_ (
    .A(_0235_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__buf_1 _0610_ (
    .A(_0252_),
    .X(_0253_)
  );
  sky130_fd_sc_hd__buf_1 _0611_ (
    .A(_0238_),
    .X(_0254_)
  );
  sky130_fd_sc_hd__buf_1 _0612_ (
    .A(_0254_),
    .X(_0255_)
  );
  sky130_fd_sc_hd__a22o_2 _0613_ (
    .A1(\reg_0[15] ),
    .A2(_0253_),
    .B1(wbm_dat_i[15]),
    .B2(_0255_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__buf_1 _0614_ (
    .A(_0247_),
    .X(_0256_)
  );
  sky130_fd_sc_hd__buf_1 _0615_ (
    .A(_0256_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__a22o_2 _0616_ (
    .A1(\reg_0[14] ),
    .A2(_0253_),
    .B1(wbm_dat_i[14]),
    .B2(_0255_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__buf_1 _0617_ (
    .A(_0256_),
    .X(_0058_)
  );
  sky130_fd_sc_hd__a22o_2 _0618_ (
    .A1(\reg_0[13] ),
    .A2(_0253_),
    .B1(wbm_dat_i[13]),
    .B2(_0255_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__buf_1 _0619_ (
    .A(_0256_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__a22o_2 _0620_ (
    .A1(\reg_0[12] ),
    .A2(_0253_),
    .B1(wbm_dat_i[12]),
    .B2(_0255_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__buf_1 _0621_ (
    .A(_0256_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__buf_1 _0622_ (
    .A(_0252_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__buf_1 _0623_ (
    .A(_0254_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__a22o_2 _0624_ (
    .A1(\reg_0[11] ),
    .A2(_0257_),
    .B1(wbm_dat_i[11]),
    .B2(_0258_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__buf_1 _0625_ (
    .A(_0247_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__buf_1 _0626_ (
    .A(_0259_),
    .X(_0055_)
  );
  sky130_fd_sc_hd__a22o_2 _0627_ (
    .A1(\reg_0[10] ),
    .A2(_0257_),
    .B1(wbm_dat_i[10]),
    .B2(_0258_),
    .X(_0151_)
  );
  sky130_fd_sc_hd__buf_1 _0628_ (
    .A(_0259_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__a22o_2 _0629_ (
    .A1(\reg_0[9] ),
    .A2(_0257_),
    .B1(wbm_dat_i[9]),
    .B2(_0258_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__buf_1 _0630_ (
    .A(_0259_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__a22o_2 _0631_ (
    .A1(\reg_0[8] ),
    .A2(_0257_),
    .B1(wbm_dat_i[8]),
    .B2(_0258_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__buf_1 _0632_ (
    .A(_0259_),
    .X(_0052_)
  );
  sky130_fd_sc_hd__buf_1 _0633_ (
    .A(_0252_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__buf_1 _0634_ (
    .A(_0254_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__a22o_2 _0635_ (
    .A1(\reg_0[7] ),
    .A2(_0260_),
    .B1(wbm_dat_i[7]),
    .B2(_0261_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__buf_1 _0636_ (
    .A(_0206_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__buf_1 _0637_ (
    .A(_0262_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__buf_1 _0638_ (
    .A(_0263_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__a22o_2 _0639_ (
    .A1(\reg_0[6] ),
    .A2(_0260_),
    .B1(wbm_dat_i[6]),
    .B2(_0261_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__buf_1 _0640_ (
    .A(_0263_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__a22o_2 _0641_ (
    .A1(\reg_0[5] ),
    .A2(_0260_),
    .B1(wbm_dat_i[5]),
    .B2(_0261_),
    .X(_0146_)
  );
  sky130_fd_sc_hd__buf_1 _0642_ (
    .A(_0263_),
    .X(_0049_)
  );
  sky130_fd_sc_hd__a22o_2 _0643_ (
    .A1(\reg_0[4] ),
    .A2(_0260_),
    .B1(wbm_dat_i[4]),
    .B2(_0261_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__buf_1 _0644_ (
    .A(_0263_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__buf_1 _0645_ (
    .A(_0252_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__buf_1 _0646_ (
    .A(_0254_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__a22o_2 _0647_ (
    .A1(\reg_0[3] ),
    .A2(_0264_),
    .B1(wbm_dat_i[3]),
    .B2(_0265_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__buf_1 _0648_ (
    .A(_0262_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__buf_1 _0649_ (
    .A(_0266_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__a22o_2 _0650_ (
    .A1(\reg_0[2] ),
    .A2(_0264_),
    .B1(wbm_dat_i[2]),
    .B2(_0265_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__buf_1 _0651_ (
    .A(_0266_),
    .X(_0046_)
  );
  sky130_fd_sc_hd__a22o_2 _0652_ (
    .A1(\reg_0[1] ),
    .A2(_0264_),
    .B1(wbm_dat_i[1]),
    .B2(_0265_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__buf_1 _0653_ (
    .A(_0266_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__a22o_2 _0654_ (
    .A1(\reg_0[0] ),
    .A2(_0264_),
    .B1(wbm_dat_i[0]),
    .B2(_0265_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__buf_1 _0655_ (
    .A(_0266_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__or2_2 _0656_ (
    .A(_0196_),
    .B(reg_ack),
    .X(_0267_)
  );
  sky130_fd_sc_hd__inv_2 _0657_ (
    .A(_0267_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__buf_1 _0658_ (
    .A(_0268_),
    .X(_0269_)
  );
  sky130_fd_sc_hd__buf_1 _0659_ (
    .A(_0269_),
    .X(_0000_)
  );
  sky130_fd_sc_hd__inv_2 _0660_ (
    .A(\reg_rdata[31] ),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__buf_1 _0661_ (
    .A(_0267_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__buf_1 _0662_ (
    .A(_0271_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__inv_2 _0663_ (
    .A(\reg_1[31] ),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__buf_1 _0664_ (
    .A(_0198_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__buf_1 _0665_ (
    .A(_0274_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__inv_2 _0666_ (
    .A(\reg_0[31] ),
    .Y(_0276_)
  );
  sky130_fd_sc_hd__buf_1 _0667_ (
    .A(_0234_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__buf_1 _0668_ (
    .A(_0277_),
    .X(_0278_)
  );
  sky130_fd_sc_hd__o22a_2 _0669_ (
    .A1(_0273_),
    .A2(_0275_),
    .B1(_0276_),
    .B2(_0278_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__o22ai_2 _0670_ (
    .A1(_0270_),
    .A2(_0000_),
    .B1(_0272_),
    .B2(_0279_),
    .Y(_0140_)
  );
  sky130_fd_sc_hd__buf_1 _0671_ (
    .A(_0262_),
    .X(_0280_)
  );
  sky130_fd_sc_hd__buf_1 _0672_ (
    .A(_0280_),
    .X(_0043_)
  );
  sky130_fd_sc_hd__inv_2 _0673_ (
    .A(\reg_rdata[30] ),
    .Y(_0281_)
  );
  sky130_fd_sc_hd__inv_2 _0674_ (
    .A(\reg_1[30] ),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__inv_2 _0675_ (
    .A(\reg_0[30] ),
    .Y(_0283_)
  );
  sky130_fd_sc_hd__o22a_2 _0676_ (
    .A1(_0282_),
    .A2(_0275_),
    .B1(_0283_),
    .B2(_0278_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__o22ai_2 _0677_ (
    .A1(_0281_),
    .A2(_0000_),
    .B1(_0272_),
    .B2(_0284_),
    .Y(_0139_)
  );
  sky130_fd_sc_hd__buf_1 _0678_ (
    .A(_0280_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__inv_2 _0679_ (
    .A(\reg_rdata[29] ),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__inv_2 _0680_ (
    .A(\reg_1[29] ),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__inv_2 _0681_ (
    .A(\reg_0[29] ),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__o22a_2 _0682_ (
    .A1(_0286_),
    .A2(_0275_),
    .B1(_0287_),
    .B2(_0278_),
    .X(_0288_)
  );
  sky130_fd_sc_hd__o22ai_2 _0683_ (
    .A1(_0285_),
    .A2(_0000_),
    .B1(_0272_),
    .B2(_0288_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__buf_1 _0684_ (
    .A(_0280_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__inv_2 _0685_ (
    .A(\reg_rdata[28] ),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__buf_1 _0686_ (
    .A(_0269_),
    .X(_0290_)
  );
  sky130_fd_sc_hd__inv_2 _0687_ (
    .A(\reg_1[28] ),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__buf_1 _0688_ (
    .A(_0274_),
    .X(_0292_)
  );
  sky130_fd_sc_hd__inv_2 _0689_ (
    .A(\reg_0[28] ),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__o22a_2 _0690_ (
    .A1(_0291_),
    .A2(_0292_),
    .B1(_0293_),
    .B2(_0278_),
    .X(_0294_)
  );
  sky130_fd_sc_hd__o22ai_2 _0691_ (
    .A1(_0289_),
    .A2(_0290_),
    .B1(_0272_),
    .B2(_0294_),
    .Y(_0137_)
  );
  sky130_fd_sc_hd__buf_1 _0692_ (
    .A(_0280_),
    .X(_0040_)
  );
  sky130_fd_sc_hd__inv_2 _0693_ (
    .A(\reg_rdata[27] ),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__buf_1 _0694_ (
    .A(_0271_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__inv_2 _0695_ (
    .A(\reg_1[27] ),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__inv_2 _0696_ (
    .A(\reg_0[27] ),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__buf_1 _0697_ (
    .A(_0277_),
    .X(_0299_)
  );
  sky130_fd_sc_hd__o22a_2 _0698_ (
    .A1(_0297_),
    .A2(_0292_),
    .B1(_0298_),
    .B2(_0299_),
    .X(_0300_)
  );
  sky130_fd_sc_hd__o22ai_2 _0699_ (
    .A1(_0295_),
    .A2(_0290_),
    .B1(_0296_),
    .B2(_0300_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__buf_1 _0700_ (
    .A(_0262_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__buf_1 _0701_ (
    .A(_0301_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__inv_2 _0702_ (
    .A(\reg_rdata[26] ),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__inv_2 _0703_ (
    .A(\reg_1[26] ),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__inv_2 _0704_ (
    .A(\reg_0[26] ),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__o22a_2 _0705_ (
    .A1(_0303_),
    .A2(_0292_),
    .B1(_0304_),
    .B2(_0299_),
    .X(_0305_)
  );
  sky130_fd_sc_hd__o22ai_2 _0706_ (
    .A1(_0302_),
    .A2(_0290_),
    .B1(_0296_),
    .B2(_0305_),
    .Y(_0135_)
  );
  sky130_fd_sc_hd__buf_1 _0707_ (
    .A(_0301_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__inv_2 _0708_ (
    .A(\reg_rdata[25] ),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__inv_2 _0709_ (
    .A(\reg_1[25] ),
    .Y(_0307_)
  );
  sky130_fd_sc_hd__inv_2 _0710_ (
    .A(\reg_0[25] ),
    .Y(_0308_)
  );
  sky130_fd_sc_hd__o22a_2 _0711_ (
    .A1(_0307_),
    .A2(_0292_),
    .B1(_0308_),
    .B2(_0299_),
    .X(_0309_)
  );
  sky130_fd_sc_hd__o22ai_2 _0712_ (
    .A1(_0306_),
    .A2(_0290_),
    .B1(_0296_),
    .B2(_0309_),
    .Y(_0134_)
  );
  sky130_fd_sc_hd__buf_1 _0713_ (
    .A(_0301_),
    .X(_0037_)
  );
  sky130_fd_sc_hd__inv_2 _0714_ (
    .A(\reg_rdata[24] ),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__buf_1 _0715_ (
    .A(_0269_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__inv_2 _0716_ (
    .A(\reg_1[24] ),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__buf_1 _0717_ (
    .A(_0274_),
    .X(_0313_)
  );
  sky130_fd_sc_hd__inv_2 _0718_ (
    .A(\reg_0[24] ),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__o22a_2 _0719_ (
    .A1(_0312_),
    .A2(_0313_),
    .B1(_0314_),
    .B2(_0299_),
    .X(_0315_)
  );
  sky130_fd_sc_hd__o22ai_2 _0720_ (
    .A1(_0310_),
    .A2(_0311_),
    .B1(_0296_),
    .B2(_0315_),
    .Y(_0133_)
  );
  sky130_fd_sc_hd__buf_1 _0721_ (
    .A(_0301_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__inv_2 _0722_ (
    .A(\reg_rdata[23] ),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__buf_1 _0723_ (
    .A(_0271_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__inv_2 _0724_ (
    .A(\reg_1[23] ),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__inv_2 _0725_ (
    .A(\reg_0[23] ),
    .Y(_0319_)
  );
  sky130_fd_sc_hd__buf_1 _0726_ (
    .A(_0277_),
    .X(_0320_)
  );
  sky130_fd_sc_hd__o22a_2 _0727_ (
    .A1(_0318_),
    .A2(_0313_),
    .B1(_0319_),
    .B2(_0320_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__o22ai_2 _0728_ (
    .A1(_0316_),
    .A2(_0311_),
    .B1(_0317_),
    .B2(_0321_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__buf_1 _0729_ (
    .A(_0206_),
    .X(_0322_)
  );
  sky130_fd_sc_hd__buf_1 _0730_ (
    .A(_0322_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__buf_1 _0731_ (
    .A(_0323_),
    .X(_0035_)
  );
  sky130_fd_sc_hd__inv_2 _0732_ (
    .A(\reg_rdata[22] ),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__inv_2 _0733_ (
    .A(\reg_1[22] ),
    .Y(_0325_)
  );
  sky130_fd_sc_hd__inv_2 _0734_ (
    .A(\reg_0[22] ),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__o22a_2 _0735_ (
    .A1(_0325_),
    .A2(_0313_),
    .B1(_0326_),
    .B2(_0320_),
    .X(_0327_)
  );
  sky130_fd_sc_hd__o22ai_2 _0736_ (
    .A1(_0324_),
    .A2(_0311_),
    .B1(_0317_),
    .B2(_0327_),
    .Y(_0131_)
  );
  sky130_fd_sc_hd__buf_1 _0737_ (
    .A(_0323_),
    .X(_0034_)
  );
  sky130_fd_sc_hd__inv_2 _0738_ (
    .A(\reg_rdata[21] ),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__inv_2 _0739_ (
    .A(\reg_1[21] ),
    .Y(_0329_)
  );
  sky130_fd_sc_hd__inv_2 _0740_ (
    .A(\reg_0[21] ),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__o22a_2 _0741_ (
    .A1(_0329_),
    .A2(_0313_),
    .B1(_0330_),
    .B2(_0320_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__o22ai_2 _0742_ (
    .A1(_0328_),
    .A2(_0311_),
    .B1(_0317_),
    .B2(_0331_),
    .Y(_0130_)
  );
  sky130_fd_sc_hd__buf_1 _0743_ (
    .A(_0323_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__inv_2 _0744_ (
    .A(\reg_rdata[20] ),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__buf_1 _0745_ (
    .A(_0268_),
    .X(_0333_)
  );
  sky130_fd_sc_hd__buf_1 _0746_ (
    .A(_0333_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__inv_2 _0747_ (
    .A(\reg_1[20] ),
    .Y(_0335_)
  );
  sky130_fd_sc_hd__buf_1 _0748_ (
    .A(_0274_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__inv_2 _0749_ (
    .A(\reg_0[20] ),
    .Y(_0337_)
  );
  sky130_fd_sc_hd__o22a_2 _0750_ (
    .A1(_0335_),
    .A2(_0336_),
    .B1(_0337_),
    .B2(_0320_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__o22ai_2 _0751_ (
    .A1(_0332_),
    .A2(_0334_),
    .B1(_0317_),
    .B2(_0338_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__buf_1 _0752_ (
    .A(_0323_),
    .X(_0032_)
  );
  sky130_fd_sc_hd__inv_2 _0753_ (
    .A(\reg_rdata[19] ),
    .Y(_0339_)
  );
  sky130_fd_sc_hd__buf_1 _0754_ (
    .A(_0271_),
    .X(_0340_)
  );
  sky130_fd_sc_hd__inv_2 _0755_ (
    .A(\reg_1[19] ),
    .Y(_0341_)
  );
  sky130_fd_sc_hd__inv_2 _0756_ (
    .A(\reg_0[19] ),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__buf_1 _0757_ (
    .A(_0277_),
    .X(_0343_)
  );
  sky130_fd_sc_hd__o22a_2 _0758_ (
    .A1(_0341_),
    .A2(_0336_),
    .B1(_0342_),
    .B2(_0343_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__o22ai_2 _0759_ (
    .A1(_0339_),
    .A2(_0334_),
    .B1(_0340_),
    .B2(_0344_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__buf_1 _0760_ (
    .A(_0322_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__buf_1 _0761_ (
    .A(_0345_),
    .X(_0031_)
  );
  sky130_fd_sc_hd__inv_2 _0762_ (
    .A(\reg_rdata[18] ),
    .Y(_0346_)
  );
  sky130_fd_sc_hd__inv_2 _0763_ (
    .A(\reg_1[18] ),
    .Y(_0347_)
  );
  sky130_fd_sc_hd__inv_2 _0764_ (
    .A(\reg_0[18] ),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__o22a_2 _0765_ (
    .A1(_0347_),
    .A2(_0336_),
    .B1(_0348_),
    .B2(_0343_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__o22ai_2 _0766_ (
    .A1(_0346_),
    .A2(_0334_),
    .B1(_0340_),
    .B2(_0349_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__buf_1 _0767_ (
    .A(_0345_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__inv_2 _0768_ (
    .A(\reg_rdata[17] ),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__inv_2 _0769_ (
    .A(\reg_1[17] ),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__inv_2 _0770_ (
    .A(\reg_0[17] ),
    .Y(_0352_)
  );
  sky130_fd_sc_hd__o22a_2 _0771_ (
    .A1(_0351_),
    .A2(_0336_),
    .B1(_0352_),
    .B2(_0343_),
    .X(_0353_)
  );
  sky130_fd_sc_hd__o22ai_2 _0772_ (
    .A1(_0350_),
    .A2(_0334_),
    .B1(_0340_),
    .B2(_0353_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__buf_1 _0773_ (
    .A(_0345_),
    .X(_0029_)
  );
  sky130_fd_sc_hd__inv_2 _0774_ (
    .A(\reg_rdata[16] ),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__buf_1 _0775_ (
    .A(_0333_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__inv_2 _0776_ (
    .A(\reg_1[16] ),
    .Y(_0356_)
  );
  sky130_fd_sc_hd__buf_1 _0777_ (
    .A(_0198_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__buf_1 _0778_ (
    .A(_0357_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__inv_2 _0779_ (
    .A(\reg_0[16] ),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__o22a_2 _0780_ (
    .A1(_0356_),
    .A2(_0358_),
    .B1(_0359_),
    .B2(_0343_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__o22ai_2 _0781_ (
    .A1(_0354_),
    .A2(_0355_),
    .B1(_0340_),
    .B2(_0360_),
    .Y(_0125_)
  );
  sky130_fd_sc_hd__buf_1 _0782_ (
    .A(_0345_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__inv_2 _0783_ (
    .A(\reg_rdata[15] ),
    .Y(_0361_)
  );
  sky130_fd_sc_hd__buf_1 _0784_ (
    .A(_0267_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__buf_1 _0785_ (
    .A(_0362_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__inv_2 _0786_ (
    .A(\reg_1[15] ),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__inv_2 _0787_ (
    .A(\reg_0[15] ),
    .Y(_0365_)
  );
  sky130_fd_sc_hd__buf_1 _0788_ (
    .A(_0234_),
    .X(_0366_)
  );
  sky130_fd_sc_hd__buf_1 _0789_ (
    .A(_0366_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__o22a_2 _0790_ (
    .A1(_0364_),
    .A2(_0358_),
    .B1(_0365_),
    .B2(_0367_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__o22ai_2 _0791_ (
    .A1(_0361_),
    .A2(_0355_),
    .B1(_0363_),
    .B2(_0368_),
    .Y(_0124_)
  );
  sky130_fd_sc_hd__buf_1 _0792_ (
    .A(_0322_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__buf_1 _0793_ (
    .A(_0369_),
    .X(_0027_)
  );
  sky130_fd_sc_hd__inv_2 _0794_ (
    .A(\reg_rdata[14] ),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__inv_2 _0795_ (
    .A(\reg_1[14] ),
    .Y(_0371_)
  );
  sky130_fd_sc_hd__inv_2 _0796_ (
    .A(\reg_0[14] ),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__o22a_2 _0797_ (
    .A1(_0371_),
    .A2(_0358_),
    .B1(_0372_),
    .B2(_0367_),
    .X(_0373_)
  );
  sky130_fd_sc_hd__o22ai_2 _0798_ (
    .A1(_0370_),
    .A2(_0355_),
    .B1(_0363_),
    .B2(_0373_),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__buf_1 _0799_ (
    .A(_0369_),
    .X(_0026_)
  );
  sky130_fd_sc_hd__inv_2 _0800_ (
    .A(\reg_rdata[13] ),
    .Y(_0374_)
  );
  sky130_fd_sc_hd__inv_2 _0801_ (
    .A(\reg_1[13] ),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__inv_2 _0802_ (
    .A(\reg_0[13] ),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__o22a_2 _0803_ (
    .A1(_0375_),
    .A2(_0358_),
    .B1(_0376_),
    .B2(_0367_),
    .X(_0377_)
  );
  sky130_fd_sc_hd__o22ai_2 _0804_ (
    .A1(_0374_),
    .A2(_0355_),
    .B1(_0363_),
    .B2(_0377_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__buf_1 _0805_ (
    .A(_0369_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__inv_2 _0806_ (
    .A(\reg_rdata[12] ),
    .Y(_0378_)
  );
  sky130_fd_sc_hd__buf_1 _0807_ (
    .A(_0333_),
    .X(_0379_)
  );
  sky130_fd_sc_hd__inv_2 _0808_ (
    .A(\reg_1[12] ),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__buf_1 _0809_ (
    .A(_0357_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__inv_2 _0810_ (
    .A(\reg_0[12] ),
    .Y(_0382_)
  );
  sky130_fd_sc_hd__o22a_2 _0811_ (
    .A1(_0380_),
    .A2(_0381_),
    .B1(_0382_),
    .B2(_0367_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__o22ai_2 _0812_ (
    .A1(_0378_),
    .A2(_0379_),
    .B1(_0363_),
    .B2(_0383_),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__buf_1 _0813_ (
    .A(_0369_),
    .X(_0024_)
  );
  sky130_fd_sc_hd__inv_2 _0814_ (
    .A(\reg_rdata[11] ),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__buf_1 _0815_ (
    .A(_0362_),
    .X(_0385_)
  );
  sky130_fd_sc_hd__inv_2 _0816_ (
    .A(\reg_1[11] ),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__inv_2 _0817_ (
    .A(\reg_0[11] ),
    .Y(_0387_)
  );
  sky130_fd_sc_hd__buf_1 _0818_ (
    .A(_0366_),
    .X(_0388_)
  );
  sky130_fd_sc_hd__o22a_2 _0819_ (
    .A1(_0386_),
    .A2(_0381_),
    .B1(_0387_),
    .B2(_0388_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__o22ai_2 _0820_ (
    .A1(_0384_),
    .A2(_0379_),
    .B1(_0385_),
    .B2(_0389_),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__buf_1 _0821_ (
    .A(_0322_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__buf_1 _0822_ (
    .A(_0390_),
    .X(_0023_)
  );
  sky130_fd_sc_hd__inv_2 _0823_ (
    .A(\reg_rdata[10] ),
    .Y(_0391_)
  );
  sky130_fd_sc_hd__inv_2 _0824_ (
    .A(\reg_1[10] ),
    .Y(_0392_)
  );
  sky130_fd_sc_hd__inv_2 _0825_ (
    .A(\reg_0[10] ),
    .Y(_0393_)
  );
  sky130_fd_sc_hd__o22a_2 _0826_ (
    .A1(_0392_),
    .A2(_0381_),
    .B1(_0393_),
    .B2(_0388_),
    .X(_0394_)
  );
  sky130_fd_sc_hd__o22ai_2 _0827_ (
    .A1(_0391_),
    .A2(_0379_),
    .B1(_0385_),
    .B2(_0394_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__buf_1 _0828_ (
    .A(_0390_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__inv_2 _0829_ (
    .A(\reg_rdata[9] ),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__inv_2 _0830_ (
    .A(\reg_1[9] ),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__inv_2 _0831_ (
    .A(\reg_0[9] ),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__o22a_2 _0832_ (
    .A1(_0396_),
    .A2(_0381_),
    .B1(_0397_),
    .B2(_0388_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__o22ai_2 _0833_ (
    .A1(_0395_),
    .A2(_0379_),
    .B1(_0385_),
    .B2(_0398_),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__buf_1 _0834_ (
    .A(_0390_),
    .X(_0021_)
  );
  sky130_fd_sc_hd__inv_2 _0835_ (
    .A(\reg_rdata[8] ),
    .Y(_0399_)
  );
  sky130_fd_sc_hd__buf_1 _0836_ (
    .A(_0333_),
    .X(_0400_)
  );
  sky130_fd_sc_hd__inv_2 _0837_ (
    .A(\reg_1[8] ),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__buf_1 _0838_ (
    .A(_0357_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__inv_2 _0839_ (
    .A(\reg_0[8] ),
    .Y(_0403_)
  );
  sky130_fd_sc_hd__o22a_2 _0840_ (
    .A1(_0401_),
    .A2(_0402_),
    .B1(_0403_),
    .B2(_0388_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__o22ai_2 _0841_ (
    .A1(_0399_),
    .A2(_0400_),
    .B1(_0385_),
    .B2(_0404_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__buf_1 _0842_ (
    .A(_0390_),
    .X(_0020_)
  );
  sky130_fd_sc_hd__inv_2 _0843_ (
    .A(\reg_rdata[7] ),
    .Y(_0405_)
  );
  sky130_fd_sc_hd__buf_1 _0844_ (
    .A(_0362_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__inv_2 _0845_ (
    .A(\reg_1[7] ),
    .Y(_0407_)
  );
  sky130_fd_sc_hd__inv_2 _0846_ (
    .A(\reg_0[7] ),
    .Y(_0408_)
  );
  sky130_fd_sc_hd__buf_1 _0847_ (
    .A(_0366_),
    .X(_0409_)
  );
  sky130_fd_sc_hd__o22a_2 _0848_ (
    .A1(_0407_),
    .A2(_0402_),
    .B1(_0408_),
    .B2(_0409_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__o22ai_2 _0849_ (
    .A1(_0405_),
    .A2(_0400_),
    .B1(_0406_),
    .B2(_0410_),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__buf_1 _0850_ (
    .A(_0213_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__buf_1 _0851_ (
    .A(_0411_),
    .X(_0019_)
  );
  sky130_fd_sc_hd__inv_2 _0852_ (
    .A(\reg_rdata[6] ),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__inv_2 _0853_ (
    .A(\reg_1[6] ),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__inv_2 _0854_ (
    .A(\reg_0[6] ),
    .Y(_0414_)
  );
  sky130_fd_sc_hd__o22a_2 _0855_ (
    .A1(_0413_),
    .A2(_0402_),
    .B1(_0414_),
    .B2(_0409_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__o22ai_2 _0856_ (
    .A1(_0412_),
    .A2(_0400_),
    .B1(_0406_),
    .B2(_0415_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__buf_1 _0857_ (
    .A(_0411_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__inv_2 _0858_ (
    .A(\reg_rdata[5] ),
    .Y(_0416_)
  );
  sky130_fd_sc_hd__inv_2 _0859_ (
    .A(\reg_1[5] ),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__inv_2 _0860_ (
    .A(\reg_0[5] ),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__o22a_2 _0861_ (
    .A1(_0417_),
    .A2(_0402_),
    .B1(_0418_),
    .B2(_0409_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__o22ai_2 _0862_ (
    .A1(_0416_),
    .A2(_0400_),
    .B1(_0406_),
    .B2(_0419_),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__buf_1 _0863_ (
    .A(_0411_),
    .X(_0017_)
  );
  sky130_fd_sc_hd__inv_2 _0864_ (
    .A(\reg_rdata[4] ),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__buf_1 _0865_ (
    .A(_0268_),
    .X(_0421_)
  );
  sky130_fd_sc_hd__inv_2 _0866_ (
    .A(\reg_1[4] ),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__buf_1 _0867_ (
    .A(_0357_),
    .X(_0423_)
  );
  sky130_fd_sc_hd__inv_2 _0868_ (
    .A(\reg_0[4] ),
    .Y(_0424_)
  );
  sky130_fd_sc_hd__o22a_2 _0869_ (
    .A1(_0422_),
    .A2(_0423_),
    .B1(_0424_),
    .B2(_0409_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__o22ai_2 _0870_ (
    .A1(_0420_),
    .A2(_0421_),
    .B1(_0406_),
    .B2(_0425_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__buf_1 _0871_ (
    .A(_0411_),
    .X(_0016_)
  );
  sky130_fd_sc_hd__inv_2 _0872_ (
    .A(\reg_rdata[3] ),
    .Y(_0426_)
  );
  sky130_fd_sc_hd__buf_1 _0873_ (
    .A(_0362_),
    .X(_0427_)
  );
  sky130_fd_sc_hd__inv_2 _0874_ (
    .A(\reg_1[3] ),
    .Y(_0428_)
  );
  sky130_fd_sc_hd__inv_2 _0875_ (
    .A(\reg_0[3] ),
    .Y(_0429_)
  );
  sky130_fd_sc_hd__buf_1 _0876_ (
    .A(_0366_),
    .X(_0430_)
  );
  sky130_fd_sc_hd__o22a_2 _0877_ (
    .A1(_0428_),
    .A2(_0423_),
    .B1(_0429_),
    .B2(_0430_),
    .X(_0431_)
  );
  sky130_fd_sc_hd__o22ai_2 _0878_ (
    .A1(_0426_),
    .A2(_0421_),
    .B1(_0427_),
    .B2(_0431_),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__buf_1 _0879_ (
    .A(_0213_),
    .X(_0432_)
  );
  sky130_fd_sc_hd__buf_1 _0880_ (
    .A(_0432_),
    .X(_0015_)
  );
  sky130_fd_sc_hd__inv_2 _0881_ (
    .A(\reg_rdata[2] ),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__inv_2 _0882_ (
    .A(\reg_1[2] ),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__inv_2 _0883_ (
    .A(\reg_0[2] ),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__o22a_2 _0884_ (
    .A1(_0434_),
    .A2(_0423_),
    .B1(_0435_),
    .B2(_0430_),
    .X(_0436_)
  );
  sky130_fd_sc_hd__o22ai_2 _0885_ (
    .A1(_0433_),
    .A2(_0421_),
    .B1(_0427_),
    .B2(_0436_),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__buf_1 _0886_ (
    .A(_0432_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__inv_2 _0887_ (
    .A(\reg_rdata[1] ),
    .Y(_0437_)
  );
  sky130_fd_sc_hd__inv_2 _0888_ (
    .A(\reg_1[1] ),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__inv_2 _0889_ (
    .A(\reg_0[1] ),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__o22a_2 _0890_ (
    .A1(_0438_),
    .A2(_0423_),
    .B1(_0439_),
    .B2(_0430_),
    .X(_0440_)
  );
  sky130_fd_sc_hd__o22ai_2 _0891_ (
    .A1(_0437_),
    .A2(_0421_),
    .B1(_0427_),
    .B2(_0440_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__buf_1 _0892_ (
    .A(_0432_),
    .X(_0013_)
  );
  sky130_fd_sc_hd__inv_2 _0893_ (
    .A(\reg_rdata[0] ),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__inv_2 _0894_ (
    .A(\reg_0[0] ),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__inv_2 _0895_ (
    .A(\reg_1[0] ),
    .Y(_0443_)
  );
  sky130_fd_sc_hd__o22a_2 _0896_ (
    .A1(_0442_),
    .A2(_0430_),
    .B1(_0443_),
    .B2(_0275_),
    .X(_0444_)
  );
  sky130_fd_sc_hd__o22ai_2 _0897_ (
    .A1(_0441_),
    .A2(_0269_),
    .B1(_0427_),
    .B2(_0444_),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__buf_1 _0898_ (
    .A(_0432_),
    .X(_0012_)
  );
  sky130_fd_sc_hd__buf_1 _0899_ (
    .A(_0207_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__buf_1 _0900_ (
    .A(_0196_),
    .X(_0445_)
  );
  sky130_fd_sc_hd__buf_1 _0901_ (
    .A(_0445_),
    .X(_0446_)
  );
  sky130_fd_sc_hd__inv_2 _0902_ (
    .A(reg_ack),
    .Y(_0447_)
  );
  sky130_fd_sc_hd__nor2_2 _0903_ (
    .A(_0446_),
    .B(_0447_),
    .Y(wbm_ack_o)
  );
  sky130_fd_sc_hd__o21a_2 _0904_ (
    .A1(_0446_),
    .A2(_0447_),
    .B1(wbm_stb_i),
    .X(_0001_)
  );
  sky130_fd_sc_hd__buf_1 _0905_ (
    .A(_0446_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__nor2_2 _0906_ (
    .A(_0441_),
    .B(_0448_),
    .Y(wbm_dat_o[0])
  );
  sky130_fd_sc_hd__nor2_2 _0907_ (
    .A(_0437_),
    .B(_0448_),
    .Y(wbm_dat_o[1])
  );
  sky130_fd_sc_hd__nor2_2 _0908_ (
    .A(_0433_),
    .B(_0448_),
    .Y(wbm_dat_o[2])
  );
  sky130_fd_sc_hd__nor2_2 _0909_ (
    .A(_0426_),
    .B(_0448_),
    .Y(wbm_dat_o[3])
  );
  sky130_fd_sc_hd__buf_1 _0910_ (
    .A(_0446_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__nor2_2 _0911_ (
    .A(_0420_),
    .B(_0449_),
    .Y(wbm_dat_o[4])
  );
  sky130_fd_sc_hd__nor2_2 _0912_ (
    .A(_0416_),
    .B(_0449_),
    .Y(wbm_dat_o[5])
  );
  sky130_fd_sc_hd__nor2_2 _0913_ (
    .A(_0412_),
    .B(_0449_),
    .Y(wbm_dat_o[6])
  );
  sky130_fd_sc_hd__nor2_2 _0914_ (
    .A(_0405_),
    .B(_0449_),
    .Y(wbm_dat_o[7])
  );
  sky130_fd_sc_hd__buf_1 _0915_ (
    .A(_0445_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__buf_1 _0916_ (
    .A(_0450_),
    .X(_0451_)
  );
  sky130_fd_sc_hd__nor2_2 _0917_ (
    .A(_0399_),
    .B(_0451_),
    .Y(wbm_dat_o[8])
  );
  sky130_fd_sc_hd__nor2_2 _0918_ (
    .A(_0395_),
    .B(_0451_),
    .Y(wbm_dat_o[9])
  );
  sky130_fd_sc_hd__nor2_2 _0919_ (
    .A(_0391_),
    .B(_0451_),
    .Y(wbm_dat_o[10])
  );
  sky130_fd_sc_hd__nor2_2 _0920_ (
    .A(_0384_),
    .B(_0451_),
    .Y(wbm_dat_o[11])
  );
  sky130_fd_sc_hd__buf_1 _0921_ (
    .A(_0450_),
    .X(_0452_)
  );
  sky130_fd_sc_hd__nor2_2 _0922_ (
    .A(_0378_),
    .B(_0452_),
    .Y(wbm_dat_o[12])
  );
  sky130_fd_sc_hd__nor2_2 _0923_ (
    .A(_0374_),
    .B(_0452_),
    .Y(wbm_dat_o[13])
  );
  sky130_fd_sc_hd__nor2_2 _0924_ (
    .A(_0370_),
    .B(_0452_),
    .Y(wbm_dat_o[14])
  );
  sky130_fd_sc_hd__nor2_2 _0925_ (
    .A(_0361_),
    .B(_0452_),
    .Y(wbm_dat_o[15])
  );
  sky130_fd_sc_hd__buf_1 _0926_ (
    .A(_0450_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__nor2_2 _0927_ (
    .A(_0354_),
    .B(_0453_),
    .Y(wbm_dat_o[16])
  );
  sky130_fd_sc_hd__nor2_2 _0928_ (
    .A(_0350_),
    .B(_0453_),
    .Y(wbm_dat_o[17])
  );
  sky130_fd_sc_hd__nor2_2 _0929_ (
    .A(_0346_),
    .B(_0453_),
    .Y(wbm_dat_o[18])
  );
  sky130_fd_sc_hd__nor2_2 _0930_ (
    .A(_0339_),
    .B(_0453_),
    .Y(wbm_dat_o[19])
  );
  sky130_fd_sc_hd__buf_1 _0931_ (
    .A(_0450_),
    .X(_0454_)
  );
  sky130_fd_sc_hd__nor2_2 _0932_ (
    .A(_0332_),
    .B(_0454_),
    .Y(wbm_dat_o[20])
  );
  sky130_fd_sc_hd__nor2_2 _0933_ (
    .A(_0328_),
    .B(_0454_),
    .Y(wbm_dat_o[21])
  );
  sky130_fd_sc_hd__nor2_2 _0934_ (
    .A(_0324_),
    .B(_0454_),
    .Y(wbm_dat_o[22])
  );
  sky130_fd_sc_hd__nor2_2 _0935_ (
    .A(_0316_),
    .B(_0454_),
    .Y(wbm_dat_o[23])
  );
  sky130_fd_sc_hd__buf_1 _0936_ (
    .A(_0445_),
    .X(_0455_)
  );
  sky130_fd_sc_hd__nor2_2 _0937_ (
    .A(_0310_),
    .B(_0455_),
    .Y(wbm_dat_o[24])
  );
  sky130_fd_sc_hd__nor2_2 _0938_ (
    .A(_0306_),
    .B(_0455_),
    .Y(wbm_dat_o[25])
  );
  sky130_fd_sc_hd__nor2_2 _0939_ (
    .A(_0302_),
    .B(_0455_),
    .Y(wbm_dat_o[26])
  );
  sky130_fd_sc_hd__nor2_2 _0940_ (
    .A(_0295_),
    .B(_0455_),
    .Y(wbm_dat_o[27])
  );
  sky130_fd_sc_hd__buf_1 _0941_ (
    .A(_0445_),
    .X(_0456_)
  );
  sky130_fd_sc_hd__nor2_2 _0942_ (
    .A(_0289_),
    .B(_0456_),
    .Y(wbm_dat_o[28])
  );
  sky130_fd_sc_hd__nor2_2 _0943_ (
    .A(_0285_),
    .B(_0456_),
    .Y(wbm_dat_o[29])
  );
  sky130_fd_sc_hd__nor2_2 _0944_ (
    .A(_0281_),
    .B(_0456_),
    .Y(wbm_dat_o[30])
  );
  sky130_fd_sc_hd__nor2_2 _0945_ (
    .A(_0270_),
    .B(_0456_),
    .Y(wbm_dat_o[31])
  );
  sky130_fd_sc_hd__buf_1 _0946_ (
    .A(_0207_),
    .X(_0010_)
  );
  sky130_fd_sc_hd__conb_1 _0947_ (
    .LO(wbm_err_o)
  );
  sky130_fd_sc_hd__dfrtp_2 _0948_ (
    .CLK(wbm_clk_i),
    .D(_0000_),
    .Q(reg_ack),
    .RESET_B(_0011_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0949_ (
    .CLK(wbm_clk_i),
    .D(_0001_),
    .Q(wb_req),
    .RESET_B(_0012_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0950_ (
    .CLK(wbm_clk_i),
    .D(_0109_),
    .Q(\reg_rdata[0] ),
    .RESET_B(_0013_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0951_ (
    .CLK(wbm_clk_i),
    .D(_0110_),
    .Q(\reg_rdata[1] ),
    .RESET_B(_0014_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0952_ (
    .CLK(wbm_clk_i),
    .D(_0111_),
    .Q(\reg_rdata[2] ),
    .RESET_B(_0015_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0953_ (
    .CLK(wbm_clk_i),
    .D(_0112_),
    .Q(\reg_rdata[3] ),
    .RESET_B(_0016_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0954_ (
    .CLK(wbm_clk_i),
    .D(_0113_),
    .Q(\reg_rdata[4] ),
    .RESET_B(_0017_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0955_ (
    .CLK(wbm_clk_i),
    .D(_0114_),
    .Q(\reg_rdata[5] ),
    .RESET_B(_0018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0956_ (
    .CLK(wbm_clk_i),
    .D(_0115_),
    .Q(\reg_rdata[6] ),
    .RESET_B(_0019_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0957_ (
    .CLK(wbm_clk_i),
    .D(_0116_),
    .Q(\reg_rdata[7] ),
    .RESET_B(_0020_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0958_ (
    .CLK(wbm_clk_i),
    .D(_0117_),
    .Q(\reg_rdata[8] ),
    .RESET_B(_0021_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0959_ (
    .CLK(wbm_clk_i),
    .D(_0118_),
    .Q(\reg_rdata[9] ),
    .RESET_B(_0022_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0960_ (
    .CLK(wbm_clk_i),
    .D(_0119_),
    .Q(\reg_rdata[10] ),
    .RESET_B(_0023_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0961_ (
    .CLK(wbm_clk_i),
    .D(_0120_),
    .Q(\reg_rdata[11] ),
    .RESET_B(_0024_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0962_ (
    .CLK(wbm_clk_i),
    .D(_0121_),
    .Q(\reg_rdata[12] ),
    .RESET_B(_0025_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0963_ (
    .CLK(wbm_clk_i),
    .D(_0122_),
    .Q(\reg_rdata[13] ),
    .RESET_B(_0026_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0964_ (
    .CLK(wbm_clk_i),
    .D(_0123_),
    .Q(\reg_rdata[14] ),
    .RESET_B(_0027_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0965_ (
    .CLK(wbm_clk_i),
    .D(_0124_),
    .Q(\reg_rdata[15] ),
    .RESET_B(_0028_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0966_ (
    .CLK(wbm_clk_i),
    .D(_0125_),
    .Q(\reg_rdata[16] ),
    .RESET_B(_0029_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0967_ (
    .CLK(wbm_clk_i),
    .D(_0126_),
    .Q(\reg_rdata[17] ),
    .RESET_B(_0030_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0968_ (
    .CLK(wbm_clk_i),
    .D(_0127_),
    .Q(\reg_rdata[18] ),
    .RESET_B(_0031_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0969_ (
    .CLK(wbm_clk_i),
    .D(_0128_),
    .Q(\reg_rdata[19] ),
    .RESET_B(_0032_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0970_ (
    .CLK(wbm_clk_i),
    .D(_0129_),
    .Q(\reg_rdata[20] ),
    .RESET_B(_0033_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0971_ (
    .CLK(wbm_clk_i),
    .D(_0130_),
    .Q(\reg_rdata[21] ),
    .RESET_B(_0034_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0972_ (
    .CLK(wbm_clk_i),
    .D(_0131_),
    .Q(\reg_rdata[22] ),
    .RESET_B(_0035_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0973_ (
    .CLK(wbm_clk_i),
    .D(_0132_),
    .Q(\reg_rdata[23] ),
    .RESET_B(_0036_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0974_ (
    .CLK(wbm_clk_i),
    .D(_0133_),
    .Q(\reg_rdata[24] ),
    .RESET_B(_0037_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0975_ (
    .CLK(wbm_clk_i),
    .D(_0134_),
    .Q(\reg_rdata[25] ),
    .RESET_B(_0038_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0976_ (
    .CLK(wbm_clk_i),
    .D(_0135_),
    .Q(\reg_rdata[26] ),
    .RESET_B(_0039_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0977_ (
    .CLK(wbm_clk_i),
    .D(_0136_),
    .Q(\reg_rdata[27] ),
    .RESET_B(_0040_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0978_ (
    .CLK(wbm_clk_i),
    .D(_0137_),
    .Q(\reg_rdata[28] ),
    .RESET_B(_0041_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0979_ (
    .CLK(wbm_clk_i),
    .D(_0138_),
    .Q(\reg_rdata[29] ),
    .RESET_B(_0042_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0980_ (
    .CLK(wbm_clk_i),
    .D(_0139_),
    .Q(\reg_rdata[30] ),
    .RESET_B(_0043_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0981_ (
    .CLK(wbm_clk_i),
    .D(_0140_),
    .Q(\reg_rdata[31] ),
    .RESET_B(_0044_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0982_ (
    .CLK(wbm_clk_i),
    .D(_0141_),
    .Q(\reg_0[0] ),
    .RESET_B(_0045_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0983_ (
    .CLK(wbm_clk_i),
    .D(_0142_),
    .Q(\reg_0[1] ),
    .RESET_B(_0046_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0984_ (
    .CLK(wbm_clk_i),
    .D(_0143_),
    .Q(\reg_0[2] ),
    .RESET_B(_0047_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0985_ (
    .CLK(wbm_clk_i),
    .D(_0144_),
    .Q(\reg_0[3] ),
    .RESET_B(_0048_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0986_ (
    .CLK(wbm_clk_i),
    .D(_0145_),
    .Q(\reg_0[4] ),
    .RESET_B(_0049_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0987_ (
    .CLK(wbm_clk_i),
    .D(_0146_),
    .Q(\reg_0[5] ),
    .RESET_B(_0050_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0988_ (
    .CLK(wbm_clk_i),
    .D(_0147_),
    .Q(\reg_0[6] ),
    .RESET_B(_0051_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0989_ (
    .CLK(wbm_clk_i),
    .D(_0148_),
    .Q(\reg_0[7] ),
    .RESET_B(_0052_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0990_ (
    .CLK(wbm_clk_i),
    .D(_0149_),
    .Q(\reg_0[8] ),
    .RESET_B(_0053_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0991_ (
    .CLK(wbm_clk_i),
    .D(_0150_),
    .Q(\reg_0[9] ),
    .RESET_B(_0054_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0992_ (
    .CLK(wbm_clk_i),
    .D(_0151_),
    .Q(\reg_0[10] ),
    .RESET_B(_0055_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0993_ (
    .CLK(wbm_clk_i),
    .D(_0152_),
    .Q(\reg_0[11] ),
    .RESET_B(_0056_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0994_ (
    .CLK(wbm_clk_i),
    .D(_0153_),
    .Q(\reg_0[12] ),
    .RESET_B(_0057_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0995_ (
    .CLK(wbm_clk_i),
    .D(_0154_),
    .Q(\reg_0[13] ),
    .RESET_B(_0058_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0996_ (
    .CLK(wbm_clk_i),
    .D(_0155_),
    .Q(\reg_0[14] ),
    .RESET_B(_0059_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0997_ (
    .CLK(wbm_clk_i),
    .D(_0156_),
    .Q(\reg_0[15] ),
    .RESET_B(_0060_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0998_ (
    .CLK(wbm_clk_i),
    .D(_0157_),
    .Q(\reg_0[16] ),
    .RESET_B(_0061_)
  );
  sky130_fd_sc_hd__dfrtp_2 _0999_ (
    .CLK(wbm_clk_i),
    .D(_0158_),
    .Q(\reg_0[17] ),
    .RESET_B(_0062_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1000_ (
    .CLK(wbm_clk_i),
    .D(_0159_),
    .Q(\reg_0[18] ),
    .RESET_B(_0063_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1001_ (
    .CLK(wbm_clk_i),
    .D(_0160_),
    .Q(\reg_0[19] ),
    .RESET_B(_0064_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1002_ (
    .CLK(wbm_clk_i),
    .D(_0161_),
    .Q(\reg_0[20] ),
    .RESET_B(_0065_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1003_ (
    .CLK(wbm_clk_i),
    .D(_0162_),
    .Q(\reg_0[21] ),
    .RESET_B(_0066_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1004_ (
    .CLK(wbm_clk_i),
    .D(_0163_),
    .Q(\reg_0[22] ),
    .RESET_B(_0067_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1005_ (
    .CLK(wbm_clk_i),
    .D(_0164_),
    .Q(\reg_0[23] ),
    .RESET_B(_0068_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1006_ (
    .CLK(wbm_clk_i),
    .D(_0165_),
    .Q(\reg_0[24] ),
    .RESET_B(_0069_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1007_ (
    .CLK(wbm_clk_i),
    .D(_0166_),
    .Q(\reg_0[25] ),
    .RESET_B(_0070_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1008_ (
    .CLK(wbm_clk_i),
    .D(_0167_),
    .Q(\reg_0[26] ),
    .RESET_B(_0071_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1009_ (
    .CLK(wbm_clk_i),
    .D(_0168_),
    .Q(\reg_0[27] ),
    .RESET_B(_0072_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1010_ (
    .CLK(wbm_clk_i),
    .D(_0169_),
    .Q(\reg_0[28] ),
    .RESET_B(_0073_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1011_ (
    .CLK(wbm_clk_i),
    .D(_0170_),
    .Q(\reg_0[29] ),
    .RESET_B(_0074_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1012_ (
    .CLK(wbm_clk_i),
    .D(_0171_),
    .Q(\reg_0[30] ),
    .RESET_B(_0075_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1013_ (
    .CLK(wbm_clk_i),
    .D(_0172_),
    .Q(\reg_0[31] ),
    .RESET_B(_0076_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1014_ (
    .CLK(wbm_clk_i),
    .D(_0173_),
    .Q(\reg_1[0] ),
    .RESET_B(_0077_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1015_ (
    .CLK(wbm_clk_i),
    .D(_0174_),
    .Q(\reg_1[1] ),
    .RESET_B(_0078_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1016_ (
    .CLK(wbm_clk_i),
    .D(_0175_),
    .Q(\reg_1[2] ),
    .RESET_B(_0079_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1017_ (
    .CLK(wbm_clk_i),
    .D(_0176_),
    .Q(\reg_1[3] ),
    .RESET_B(_0080_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1018_ (
    .CLK(wbm_clk_i),
    .D(_0177_),
    .Q(\reg_1[4] ),
    .RESET_B(_0081_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1019_ (
    .CLK(wbm_clk_i),
    .D(_0178_),
    .Q(\reg_1[5] ),
    .RESET_B(_0082_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1020_ (
    .CLK(wbm_clk_i),
    .D(_0179_),
    .Q(\reg_1[6] ),
    .RESET_B(_0083_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1021_ (
    .CLK(wbm_clk_i),
    .D(_0180_),
    .Q(\reg_1[7] ),
    .RESET_B(_0084_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1022_ (
    .CLK(wbm_clk_i),
    .D(_0181_),
    .Q(\reg_1[8] ),
    .RESET_B(_0085_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1023_ (
    .CLK(wbm_clk_i),
    .D(_0182_),
    .Q(\reg_1[9] ),
    .RESET_B(_0086_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1024_ (
    .CLK(wbm_clk_i),
    .D(_0183_),
    .Q(\reg_1[10] ),
    .RESET_B(_0087_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1025_ (
    .CLK(wbm_clk_i),
    .D(_0184_),
    .Q(\reg_1[11] ),
    .RESET_B(_0088_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1026_ (
    .CLK(wbm_clk_i),
    .D(_0185_),
    .Q(\reg_1[12] ),
    .RESET_B(_0089_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1027_ (
    .CLK(wbm_clk_i),
    .D(_0186_),
    .Q(\reg_1[13] ),
    .RESET_B(_0090_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1028_ (
    .CLK(wbm_clk_i),
    .D(_0187_),
    .Q(\reg_1[14] ),
    .RESET_B(_0091_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1029_ (
    .CLK(wbm_clk_i),
    .D(_0188_),
    .Q(\reg_1[15] ),
    .RESET_B(_0092_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1030_ (
    .CLK(wbm_clk_i),
    .D(_0189_),
    .Q(\reg_1[16] ),
    .RESET_B(_0093_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1031_ (
    .CLK(wbm_clk_i),
    .D(_0190_),
    .Q(\reg_1[17] ),
    .RESET_B(_0094_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1032_ (
    .CLK(wbm_clk_i),
    .D(_0191_),
    .Q(\reg_1[18] ),
    .RESET_B(_0095_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1033_ (
    .CLK(wbm_clk_i),
    .D(_0192_),
    .Q(\reg_1[19] ),
    .RESET_B(_0096_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1034_ (
    .CLK(wbm_clk_i),
    .D(_0193_),
    .Q(\reg_1[20] ),
    .RESET_B(_0097_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1035_ (
    .CLK(wbm_clk_i),
    .D(_0194_),
    .Q(\reg_1[21] ),
    .RESET_B(_0098_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1036_ (
    .CLK(wbm_clk_i),
    .D(_0195_),
    .Q(\reg_1[22] ),
    .RESET_B(_0099_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1037_ (
    .CLK(wbm_clk_i),
    .D(_0100_),
    .Q(\reg_1[23] ),
    .RESET_B(_0002_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1038_ (
    .CLK(wbm_clk_i),
    .D(_0101_),
    .Q(\reg_1[24] ),
    .RESET_B(_0003_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1039_ (
    .CLK(wbm_clk_i),
    .D(_0102_),
    .Q(\reg_1[25] ),
    .RESET_B(_0004_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1040_ (
    .CLK(wbm_clk_i),
    .D(_0103_),
    .Q(\reg_1[26] ),
    .RESET_B(_0005_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1041_ (
    .CLK(wbm_clk_i),
    .D(_0104_),
    .Q(\reg_1[27] ),
    .RESET_B(_0006_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1042_ (
    .CLK(wbm_clk_i),
    .D(_0105_),
    .Q(\reg_1[28] ),
    .RESET_B(_0007_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1043_ (
    .CLK(wbm_clk_i),
    .D(_0106_),
    .Q(\reg_1[29] ),
    .RESET_B(_0008_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1044_ (
    .CLK(wbm_clk_i),
    .D(_0107_),
    .Q(\reg_1[30] ),
    .RESET_B(_0009_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1045_ (
    .CLK(wbm_clk_i),
    .D(_0108_),
    .Q(\reg_1[31] ),
    .RESET_B(_0010_)
  );
endmodule
